ARG system="registry-hub.mos.ru/circuitgen/circuitgen_graph:ci_latest"

FROM ${system}

RUN apt-get update && \
  apt-get upgrade -y

RUN apt-get update && apt-get install -y \
  gdb \
  nano \
  sudo \
  vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ARG USERNAME=devuser
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
  && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME

WORKDIR /workspace
RUN chown -R $USERNAME:$USERNAME /workspace

RUN git clone https://hub.mos.ru/circuitgen/CircuitGen_Graph.git

USER $USERNAME

ENV PATH="/usr/local/bin:$PATH"
ENV CC=/usr/bin/gcc
ENV CXX=/usr/bin/g++

RUN ./TEST_BEFORE_PUSH.sh
