#pragma once
#include "CircuitGenGraph/GraphUtils.hpp"
#include <string_view>
#include <unordered_map>
namespace SequentialVerilogInstance {
using namespace CG_Graph;
static std::unordered_map<SequentialTypes, std::string_view>
    SequentialTypeToVerilog = {
        {affr, "// RST signal \"{3}\" - when it is in a logical zero state, "
               "trigger writes logical zero to the output\n"
               "\t// RST signal \"{3}\" is async - always block enables on "
               "negedge of RST\n"
               "\talways @(posedge {2} or negedge {3}) begin\n"
               "\t\tif (!{3}) {0} <= 1'b0;\n"
               "\t\telse {0} <= {1};\n"
               "\tend\n"},
        {affre, "// RST signal \"{4}\" - when it is in a logical zero state, "
                "trigger writes logical zero to the output\n"
                "\t// RST signal \"{4}\" is async - always block enables on "
                "negedge of RST\n"
                "\t// EN signal \"{3}\" - when it is in a logical one state, "
                "trigger writes data to the output\n"
                "\talways @(posedge {2} or negedge {4}) begin\n"
                "\t\tif (!{4}) {0} <= 1'b0;\n"
                "\t\telse if ({3}) {0} <= {1};\n"
                "\tend\n"},
        {affrs, "// RST signal \"{3}\" - when it is in a logical zero state, "
                "trigger writes logical zero to the output\n"
                "\t// RST signal \"{3}\" is async - always block enables on "
                "negedge of RST\n"
                "\t// SET signal \"{4}\" - when it is in a logical one state, "
                "trigger writes logical one to the output\n"
                "\talways @(posedge {2} or negedge {3}) begin\n"
                "\t\tif (!{3}) {0} <= 1'b0;\n"
                "\t\telse if ({4}) {0} <= 1'b1;\n"
                "\t\telse {0} <= {1};\n"
                "\tend\n"},
        {affrse, "// RST signal \"{4}\" - when it is in a logical zero "
                 "state, trigger writes logical zero to the output\n"
                 "\t// RST signal \"{4}\" is async - always block enables on "
                 "negedge of RST\n"
                 "\t// SET signal \"{5}\" - when it is in a logical one state, "
                 "trigger writes logical one to the output\n"
                 "\t// EN signal \"{3}\" - when it is in a logical one state, "
                 "trigger writes data to the output\n"
                 "\talways @(posedge {2} or negedge {4}) begin\n"
                 "\t\tif (!{4}) {0} <= 1'b0;\n"
                 "\t\telse if ({5}) {0} <= 1'b1;\n"
                 "\t\telse if ({3}) {0} <= {1};\n"
                 "\tend\n"},
        {latch, "// EN signal \"{2}\" - when it is in a logical one state, "
                "trigger writes data to the output\n"
                "\talways @(*) begin\n"
                "\t\tif ({2}) {0} <= {1};\n\tend\n"},
        {latchr, "// RST signal \"{3}\" - when it is in a logical zero "
                 "state, trigger writes logical zero to the output\n"
                 "\t// EN signal \"{2}\" - when it is in a logical one state, "
                 "trigger writes data to the output\n"
                 "\talways @(*) begin\n"
                 "\t\tif (!{3}) {0} <= 1'b0;\n"
                 "\t\telse if ({2}) {0} <= {1};\n"
                 "\tend\n"},
        {latchc, "// CLR signal \"{3}\" - when it is in a logical one state, "
                 "trigger writes logical zero to the output\n"
                 "\t// EN signal \"{2}\" - when it is in a logical one state, "
                 "trigger writes data to the output\n"
                 "\talways @(*) begin\n"
                 "\t\tif ({3}) {0} <= 1'b0;\n"
                 "\t\telse if ({2}) {0} <= {1};\n"
                 "\tend\n"},
        {latchs, "// SET signal \"{3}\" - when it is in a logical one state, "
                 "trigger writes logical one to the output\n"
                 "\t// EN signal \"{2}\" - when it is in a logical one state, "
                 "trigger writes data to the output\n"
                 "\talways @(*) begin\n"
                 "\t\tif ({3}) {0} <= 1'b1;\n"
                 "\t\telse if ({2}) {0} <= {1};\n"
                 "\tend\n"},
        {latchrs, "// RST signal \"{3}\" - when it is in a logical zero "
                  "state, trigger writes logical zero to the output\n"
                  "\t// SET signal \"{4}\" - when it is in a logical one "
                  "state, trigger writes logical one to the output\n"
                  "\t// EN signal \"{2}\" - when it is in a logical one state, "
                  "trigger writes data to the output\n"
                  "\talways @(*) begin\n"
                  "\t\tif (!{3}) {0} <= 1'b0;\n"
                  "\t\telse if ({4}) {0} <= 1'b1;\n"
                  "\t\telse if ({2}) {0} <= {1};\n"
                  "\tend\n"},
        {latchcs, "// CLR signal \"{3}\" - when it is in a logical one "
                  "state, trigger writes logical zero to the output\n"
                  "\t// SET signal \"{4}\" - when it is in a logical one "
                  "state, trigger writes logical one to the output\n"
                  "\t// EN signal \"{2}\" - when it is in a logical one state, "
                  "trigger writes data to the output\n"
                  "\talways @(*) begin\n"
                  "\t\tif ({3}) {0} <= 1'b0;\n"
                  "\t\telse if ({4}) {0} <= 1'b1;\n"
                  "\t\telse if ({2}) {0} <= {1};\n"
                  "\tend\n"},
        {ff, "always @(posedge {2}) begin\n"
             "\t\t{0} <= {1};\n\tend\n"},
        {ffe, "// EN signal \"{3}\" - when it is in a logical one state, "
              "trigger writes data to the output\n"
              "\talways @(posedge {2}) begin\n"
              "\t\tif ({3}) {0} <= {1};\n"
              "\tend\n"},
        {ffr, "// RST signal \"{3}\" - when it is in a logical zero state, "
              "trigger writes logical zero to the output\n"
              "\talways @(posedge {2}) begin\n"
              "\t\tif (!{3}) {0} <= 1'b0;\n"
              "\t\telse {0} <= {1};\n"
              "\tend\n"},
        {ffc, "// CLR signal \"{3}\" - when it is in a logical one state, "
              "trigger writes logical zero to the output\n"
              "\talways @(posedge {2}) begin\n"
              "\t\tif ({3}) {0} <= 1'b0;\n"
              "\t\telse {0} <= {1};\n"
              "\tend\n"},
        {SequentialTypes::ffs,
         "// SET signal \"{3}\" - when it is in a logical one state, trigger "
         "writes logical one to the output\n"
         "\talways @(posedge {2}) begin\n"
         "\t\tif ({3}) {0} <= 1'b1;\n"
         "\t\telse {0} <= {1};\n"
         "\tend\n"},
        {ffre, "// RST signal \"{4}\" - when it is in a logical zero state, "
               "trigger writes logical zero to the output\n"
               "\t// EN signal \"{3}\" - when it is in a logical one state, "
               "trigger writes data to the output\n"
               "\talways @(posedge {2}) begin\n"
               "\t\tif (!{4}) {0} <= 1'b0;\n"
               "\t\telse if ({3}) {0} <= {1};\n"
               "\tend\n"},
        {ffce, "// CLR signal \"{4}\" - when it is in a logical one state, "
               "trigger writes logical zero to the output\n"
               "\t// EN signal \"{3}\" - when it is in a logical one state, "
               "trigger writes data to the output\n"
               "\talways @(posedge {2}) begin\n"
               "\t\tif ({4}) {0} <= 1'b0;\n"
               "\t\telse if ({3}) {0} <= {1};\n"
               "\tend\n"},
        {ffse, "// SET signal \"{4}\" - when it is in a logical one state, "
               "trigger writes logical one to the output\n"
               "\t// EN signal \"{3}\" - when it is in a logical one state, "
               "trigger writes data to the output\n"
               "\talways @(posedge {2}) begin\n"
               "\t\tif ({4}) {0} <= 1'b1;\n"
               "\t\telse if ({3}) {0} <= {1};\n"
               "\tend\n"},
        {ffrs, "// RST signal \"{3}\" - when it is in a logical zero state, "
               "trigger writes logical zero to the output\n"
               "\t// SET signal \"{4}\" - when it is in a logical one state, "
               "trigger writes logical one to the output\n"
               "\talways @(posedge {2}) begin\n"
               "\t\tif (!{3}) {0} <= 1'b0;\n"
               "\t\telse if ({4}) {0} <= 1'b1;\n"
               "\t\telse {0} <= {1};\n"
               "\tend\n"},
        {ffcs, "// CLR signal \"{3}\" - when it is in a logical one state, "
               "trigger writes logical zero to the output\n"
               "\t// SET signal \"{4}\" - when it is in a logical one state, "
               "trigger writes logical one to the output\n"
               "\talways @(posedge {2}) begin\n"
               "\t\tif ({3}) {0} <= 1'b0;\n"
               "\t\telse if ({4}) {0} <= 1'b1;\n"
               "\t\telse {0} <= {1};\n"
               "\tend\n"},
        {ffrse, "// RST signal \"{4}\" - when it is in a logical zero state, "
                "trigger writes logical zero to the output\n"
                "\t// SET signal \"{5}\" - when it is in a logical one state, "
                "trigger writes logical one to the output\n"
                "\t// EN signal \"{3}\" - when it is in a logical one state, "
                "trigger writes data to the output\n"
                "\talways @(posedge {2}) begin\n"
                "\t\tif (!{4}) {0} <= 1'b0;\n"
                "\t\telse if ({5}) {0} <= 1'b1;\n"
                "\t\telse if ({3}) {0} <= {1};\n"
                "\tend\n"},
        {ffcse, "// CLR signal \"{4}\" - when it is in a logical one state, "
                "trigger writes logical zero to the output\n"
                "\t// SET signal \"{5}\" - when it is in a logical one state, "
                "trigger writes logical one to the output\n"
                "\t// EN signal \"{3}\" - when it is in a logical one state, "
                "trigger writes data to the output\n"
                "\talways @(posedge {2}) begin\n"
                "\t\tif ({4}) {0} <= 1'b0;\n"
                "\t\telse if ({5}) {0} <= 1'b1;\n"
                "\t\telse if ({3}) {0} <= {1};\n"
                "\tend\n"},
        {nff, "\talways @(negedge {2}) begin\n"
              "\t\t{0} <= {1};\n"
              "\tend\n"},
        {nffe, "// EN signal \"{3}\" - when it is in a logical one state, "
               "trigger writes data to the output\n"
               "\talways @(negedge {2}) begin\n"
               "\t\tif ({3}) {0} <= {1};\n"
               "\tend\n"},
        {nffr, "// RST signal \"{3}\" - when it is in a logical zero state, "
               "trigger writes logical zero to the output\n"
               "\talways @(negedge {2}) begin\n"
               "\t\tif (!{3}) {0} <= 1'b0;\n"
               "\t\telse {0} <= {1};\n"
               "\tend\n"},
        {nffc, "// CLR signal \"{3}\" - when it is in a logical one state, "
               "trigger writes logical zero to the output\n"
               "\talways @(negedge {2}) begin\n"
               "\t\tif ({3}) {0} <= 1'b0;\n"
               "\t\telse {0} <= {1};\n"
               "\tend\n"},
        {SequentialTypes::nffs,
         "// SET signal \"{3}\" - when it is in a logical one state, trigger "
         "writes logical one to the output\n"
         "\talways @(negedge {2}) begin\n"
         "\t\tif ({3}) {0} <= 1'b1;\n"
         "\t\telse {0} <= {1};\n"
         "\tend\n"},
        {nffre, "// RST signal \"{4}\" - when it is in a logical zero state, "
                "trigger writes logical zero to the output\n"
                "\t// EN signal \"{3}\" - when it is in a logical one state, "
                "trigger writes data to the output\n"
                "\talways @(negedge {2}) begin\n"
                "\t\tif (!{4}) {0} <= 1'b0;\n"
                "\t\telse if ({3}) {0} <= {1};\n"
                "\tend\n"},
        {nffce, "// CLR signal \"{4}\" - when it is in a logical one state, "
                "trigger writes logical zero to the output\n"
                "\t// EN signal \"{3}\" - when it is in a logical one state, "
                "trigger writes data to the output\n"
                "\talways @(negedge {2}) begin\n"
                "\t\tif ({4}) {0} <= 1'b0;\n"
                "\t\telse if ({3}) {0} <= {1};\n"
                "\tend\n"},
        {nffse, "// SET signal \"{4}\" - when it is in a logical one state, "
                "trigger writes logical one to the output\n"
                "\t// EN signal \"{3}\" - when it is in a logical one state, "
                "trigger writes data to the output\n"
                "\talways @(negedge {2}) begin\n"
                "\t\tif ({4}) {0} <= 1'b1;\n"
                "\t\telse if ({3}) {0} <= {1};\n"
                "\tend\n"},
        {nffrs, "// RST signal \"{3}\" - when it is in a logical zero state, "
                "trigger writes logical zero to the output\n"
                "\t// SET signal \"{4}\" - when it is in a logical one state, "
                "trigger writes logical one to the output\n"
                "\talways @(negedge {2}) begin\n"
                "\t\tif (!{3}) {0} <= 1'b0;\n"
                "\t\telse if ({4}) {0} <= 1'b1;\n"
                "\t\telse {0} <= {1};\n"
                "\tend\n"},
        {nffcs, "// CLR signal \"{3}\" - when it is in a logical one state, "
                "trigger writes logical zero to the output\n"
                "\t// SET signal \"{4}\" - when it is in a logical one state, "
                "trigger writes logical one to the output\n"
                "\talways @(negedge {2}) begin\n"
                "\t\tif ({3}) {0} <= 1'b0;\n"
                "\t\telse if ({4}) {0} <= 1'b1;\n"
                "\t\telse {0} <= {1};\n"
                "\tend\n"},
        {nffrse, "// RST signal \"{4}\" - when it is in a logical zero "
                 "state, trigger writes logical zero to the output\n"
                 "\t// SET signal \"{5}\" - when it is in a logical one state, "
                 "trigger writes logical one to the output\n"
                 "\t// EN signal \"{3}\" - when it is in a logical one state, "
                 "trigger writes data to the output\n"
                 "\talways @(negedge {2}) begin\n"
                 "\t\tif (!{4}) {0} <= 1'b0;\n"
                 "\t\telse if ({5}) {0} <= 1'b1;\n"
                 "\t\telse if ({3}) {0} <= {1};\n"
                 "\tend\n"},
        {nffcse, "// CLR signal \"{4}\" - when it is in a logical one state, "
                 "trigger writes logical zero to the output\n"
                 "\t// SET signal \"{5}\" - when it is in a logical one state, "
                 "trigger writes logical one to the output\n"
                 "\t// EN signal \"{3}\" - when it is in a logical one state, "
                 "trigger writes data to the output\n"
                 "\talways @(negedge {2}) begin\n"
                 "\t\tif ({4}) {0} <= 1'b0;\n"
                 "\t\telse if ({5}) {0} <= 1'b1;\n"
                 "\t\telse if ({3}) {0} <= {1};\n"
                 "\tend\n"},
        {naffrs, "// RST signal \"{3}\" - when it is in a logical zero "
                 "state, trigger writes logical zero to the output\n"
                 "\t// RST signal \"{3}\" is async - always block enables on "
                 "negedge of RST\n"
                 "\t// SET signal \"{4}\" - when it is in a logical one state, "
                 "trigger writes logical one to the output\n"
                 "\talways @(negedge {2} or negedge {3}) begin\n"
                 "\t\tif (!{3}) {0} <= 1'b0;\n"
                 "\t\telse if ({4}) {0} <= 1'b1;\n"
                 "\t\telse {0} <= {1};\n"
                 "\tend\n"},
        {naffrse, "// RST signal \"{4}\" - when it is in a logical zero "
                  "state, trigger writes logical zero to the output\n"
                  "\t// RST signal \"{4}\" is async - always block enables on "
                  "negedge of RST\n"
                  "\t// SET signal \"{5}\" - when it is in a logical one "
                  "state, trigger writes logical one to the output\n"
                  "\t// EN signal \"{3}\" - when it is in a logical one state, "
                  "trigger writes data to the output\n"
                  "\talways @(negedge {2} or negedge {4}) begin\n"
                  "\t\tif (!{4}) {0} <= 1'b0;\n"
                  "\t\telse if ({5}) {0} <= 1'b1;\n"
                  "\t\telse if ({3}) {0} <= {1};\n"
                  "\tend\n"},
        {naffr, "// RST signal \"{3}\" - when it is in a logical zero state, "
                "trigger writes logical zero to the output\n"
                "\t// RST signal \"{3}\" is async - always block enables on "
                "negedge of RST\n"
                "\talways @(negedge {2} or negedge {3}) begin\n"
                "\t\tif (!{3}) {0} <= 1'b0;\n"
                "\t\telse {0} <= {1};\n"
                "\tend\n"},
        {naffre, "// RST signal \"{4}\" - when it is in a logical zero "
                 "state, trigger writes logical zero to the output\n"
                 "\t// RST signal \"{4}\" is async - always block enables on "
                 "negedge of RST\n"
                 "\t// EN signal \"{3}\" - when it is in a logical one state, "
                 "trigger writes data to the output\n"
                 "\talways @(negedge {2} or negedge {4}) begin\n"
                 "\t\tif (!{4}) {0} <= 1'b0;\n"
                 "\t\telse if ({3}) {0} <= {1};\n"
                 "\tend\n"}};
} // namespace SequentialVerilogInstance