#include <string_view>

namespace TestData {

constexpr std::string_view SEQ_1_TEST = "module graph_0(\n"
                                        "\tclk, data, \n"
                                        "\tres\n"
                                        ");\n"
                                        "\t// Writing inputs\n"
                                        "\tinput clk, data;\n"
                                        "\t// Writing outputs\n"
                                        "\toutput res;\n"
                                        "\t// Writing registers\n"
                                        "\treg q;\n\t\n"
                                        "\talways @(posedge clk) begin\n"
                                        "\t\tq <= data;\n"
                                        "\tend\n\n"
                                        "\tassign res = q;\n"
                                        "endmodule\n";

constexpr std::string_view SEQ_2_TEST =
    "module graph_0(\n"
    "\ten, data, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput en, data;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// EN signal \"en\""
    " - when it is in a logical one state, trigger writes data to the output\n"
    "\talways @(*) begin\n"
    "\t\tif (en) q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";

constexpr std::string_view SEQ_3_TEST =
    "module graph_0(\n"
    "\ten, data, rst, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput en, data, rst;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// RST signal \"rst\""
    " - when it is in a logical zero state, trigger writes logical zero to the "
    "output\n"
    "\t// EN signal \"en\""
    " - when it is in a logical one state, trigger writes data to the output\n"
    "\talways @(*) begin\n"
    "\t\tif (!rst) q <= 1'b0;\n"
    "\t\telse if (en) q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";

constexpr std::string_view SEQ_4_TEST =
    "module graph_0(\n"
    "\ten, data, clr, set, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput en, data, clr, set;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// CLR signal \"clr\""
    " - when it is in a logical one state, trigger writes logical zero to the "
    "output\n"
    "\t// SET signal \"set\""
    " - when it is in a logical one state, trigger writes logical one to the "
    "output\n"
    "\t// EN signal \"en\""
    " - when it is in a logical one state, trigger writes data to the output\n"
    "\talways @(*) begin\n"
    "\t\tif (clr) q <= 1'b0;\n"
    "\t\telse if (set) q <= 1'b1;\n"
    "\t\telse if (en) q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";

constexpr std::string_view SEQ_5_TEST =
    "module graph_0(\n"
    "\tclk, data, rst, set, en, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput clk, data, rst, set, en;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// RST signal \"rst\" - when it is in a logical zero state, trigger "
    "writes logical zero to the output\n"
    "\t// SET signal \"set\" - when it is in a logical one state, trigger "
    "writes logical one to the output\n"
    "\t// EN signal \"en\" - when it is in a logical one state, trigger writes "
    "data to the output\n"
    "\talways @(posedge clk) begin\n"
    "\t\tif (!rst) q <= 1'b0;\n"
    "\t\telse if (set) q <= 1'b1;\n"
    "\t\telse if (en) q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";

constexpr std::string_view SEQ_6_TEST =
    "module graph_0(\n"
    "\tclk, data, rst_n, set, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput clk, data, rst_n, set;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// RST signal \"rst_n\" - when it is in a logical zero state, trigger "
    "writes logical zero to the output\n"
    "\t// RST signal \"rst_n\" is async - always block enables on negedge of "
    "RST\n"
    "\t// SET signal \"set\" - when it is in a logical one state, trigger "
    "writes logical one to the output\n"
    "\talways @(negedge clk or negedge rst_n) begin\n"
    "\t\tif (!rst_n) q <= 1'b0;\n"
    "\t\telse if (set) q <= 1'b1;\n"
    "\t\telse q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";

constexpr std::string_view SEQ_7_TEST =
    "module graph_0(\n"
    "\tclk, data, rst_n, en, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput clk, data, rst_n, en;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// RST signal \"rst_n\" - when it is in a logical zero state, trigger "
    "writes logical zero to the output\n"
    "\t// RST signal \"rst_n\" is async - always block enables on negedge of "
    "RST\n"
    "\t// EN signal \"en\" - when it is in a logical one state, trigger writes "
    "data to the output\n"
    "\talways @(posedge clk or negedge rst_n) begin\n"
    "\t\tif (!rst_n) q <= 1'b0;\n"
    "\t\telse if (en) q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";
constexpr std::string_view SEQ_8_TEST =
    "module latchrs(data, en, rst_n, set, q)\n\tinput data, en, rst_n, "
    "set;\n\toutput q;\n\t// RST signal \"rst_n\" - when it is in a logical "
    "zero state, trigger writes logical zero to the output\n\t// SET signal "
    "\"set\" - when it is in a logical one state, trigger writes logical one "
    "to the output\n\t// EN signal \"en\" - when it is in a logical one state, "
    "trigger writes data to the output\n\talways @(*) begin\n\t\tif (!rst_n) "
    "latchrs <= 1'b0;\n\t\telse if (set) latchrs <= 1'b1;\n\t\telse if (en) "
    "latchrs <= data;\n\tend\n\n\tendmodule\n\nmodule latchcs(data, en, clr, "
    "set, q)\n\tinput data, en, clr, set;\n\toutput q;\n\t// CLR signal "
    "\"clr\" - when it is in a logical one state, trigger writes logical zero "
    "to the output\n\t// SET signal \"set\" - when it is in a logical one "
    "state, trigger writes logical one to the output\n\t// EN signal \"en\" - "
    "when it is in a logical one state, trigger writes data to the "
    "output\n\talways @(*) begin\n\t\tif (clr) latchcs <= 1'b0;\n\t\telse if "
    "(set) latchcs <= 1'b1;\n\t\telse if (en) latchcs <= "
    "data;\n\tend\n\n\tendmodule\n\nmodule ff(data, clk, q)\n\tinput data, "
    "clk;\n\toutput q;\n\talways @(posedge clk) begin\n\t\tff <= "
    "data;\n\tend\n\n\tendmodule\n\nmodule graph_5(\n\tinputBus_0, inputBus_1, "
    "inputBus_2, inputBus_3, inputBus_4, anotherInputBus_0, anotherInputBus_1, "
    "anotherInputBus_2, inputVertex, \n\t);\n\t// Writing inputs\n\tinput "
    "inputVertex;\n\tinput anotherInputBus_0, anotherInputBus_1, "
    "anotherInputBus_2;\n\tinput inputBus_0, inputBus_1, inputBus_2, "
    "inputBus_3, inputBus_4;\n\t\n\t// Writing gates for main graph\n\twire "
    "or_0, or_1, or_2, or_3;\n\t\n\t// Writing registers\n\twire secondFF_0, "
    "secondFF_1, secondFF_2;\n\twire firstFF_0, firstFF_1, firstFF_2, "
    "firstFF_3, firstFF_4;\n\twire Latch_0, Latch_1, Latch_2, Latch_3, "
    "Latch_4, Latch_5;\n\twire emptyLatch_0, emptyLatch_1, emptyLatch_2, "
    "emptyLatch_3, emptyLatch_4, emptyLatch_5, emptyLatch_6, "
    "emptyLatch_7;\n\t\n\t// Writing consts\n\twire const_0_0, const_0_1, "
    "const_0_2, const_0_3, const_0_4, const_0_5, const_0_6;\n\n\tassign "
    "const_0_0 = x;\n\tassign const_0_1 = x;\n\tassign const_0_2 = "
    "x;\n\tassign const_0_3 = x;\n\tassign const_0_4 = x;\n\tassign const_0_5 "
    "= x;\n\tassign const_0_6 = x;\n\t\n\n\n\tff firstFF_0_ins "
    "(.data(inputBus_0), .clk(inputVertex), .q(firstFF_0));\n\tff "
    "firstFF_1_ins (.data(inputBus_1), .clk(inputVertex), "
    ".q(firstFF_1));\n\tff firstFF_2_ins (.data(inputBus_2), "
    ".clk(inputVertex), .q(firstFF_2));\n\tff firstFF_3_ins "
    "(.data(inputBus_3), .clk(inputVertex), .q(firstFF_3));\n\tff "
    "firstFF_4_ins (.data(inputBus_4), .clk(inputVertex), "
    ".q(firstFF_4));\n\n\tlatchcs Latch_0_ins (.data(inputBus_0), "
    ".en(inputVertex), .clr(firstFF), .set(anotherInputBus), "
    ".q(Latch_0));\n\tlatchcs Latch_1_ins (.data(inputBus_1), "
    ".en(inputVertex), .clr(firstFF), .set(anotherInputBus), "
    ".q(Latch_1));\n\tlatchcs Latch_2_ins (.data(inputBus_2), "
    ".en(inputVertex), .clr(firstFF), .set(anotherInputBus), "
    ".q(Latch_2));\n\tlatchcs Latch_3_ins (.data(inputBus_3), "
    ".en(inputVertex), .clr(firstFF), .set(anotherInputBus), "
    ".q(Latch_3));\n\tlatchcs Latch_4_ins (.data(inputBus_4), "
    ".en(inputVertex), .clr(firstFF), .set(anotherInputBus), "
    ".q(Latch_4));\n\tlatchcs Latch_5_ins (.data(inputBus_5), "
    ".en(inputVertex), .clr(firstFF), .set(anotherInputBus), "
    ".q(Latch_5));\n\n\tff secondFF_0_ins (.data(inputBus_0), "
    ".clk(anotherInputBus), .q(secondFF_0));\n\tff secondFF_1_ins "
    "(.data(inputBus_1), .clk(anotherInputBus), .q(secondFF_1));\n\tff "
    "secondFF_2_ins (.data(inputBus_2), .clk(anotherInputBus), "
    ".q(secondFF_2));\n\n\tlatchrs emptyLatch_0_ins (.data(inputBus_0), "
    ".en(inputVertex), .rst_n(const_0), .set(anotherInputBus), "
    ".q(emptyLatch_0));\n\tlatchrs emptyLatch_1_ins (.data(inputBus_1), "
    ".en(inputVertex), .rst_n(const_0), .set(anotherInputBus), "
    ".q(emptyLatch_1));\n\tlatchrs emptyLatch_2_ins (.data(inputBus_2), "
    ".en(inputVertex), .rst_n(const_0), .set(anotherInputBus), "
    ".q(emptyLatch_2));\n\tlatchrs emptyLatch_3_ins (.data(inputBus_3), "
    ".en(inputVertex), .rst_n(const_0), .set(anotherInputBus), "
    ".q(emptyLatch_3));\n\tlatchrs emptyLatch_4_ins (.data(inputBus_4), "
    ".en(inputVertex), .rst_n(const_0), .set(anotherInputBus), "
    ".q(emptyLatch_4));\n\tlatchrs emptyLatch_5_ins (.data(inputBus_5), "
    ".en(inputVertex), .rst_n(const_0), .set(anotherInputBus), "
    ".q(emptyLatch_5));\n\tlatchrs emptyLatch_6_ins (.data(inputBus_6), "
    ".en(inputVertex), .rst_n(const_0), .set(anotherInputBus), "
    ".q(emptyLatch_6));\n\tlatchrs emptyLatch_7_ins (.data(inputBus_7), "
    ".en(inputVertex), .rst_n(const_0), .set(anotherInputBus), "
    ".q(emptyLatch_7));\n\n\n\tassign or_0 = Latch_0 | secondFF_0;\n\tassign "
    "or_1 = Latch_1 | secondFF_1;\n\tassign or_2 = Latch_2 | "
    "secondFF_2;\n\tassign or_3 = Latch_3 | 1'bx;\n\t\n\nendmodule\n";
} // namespace TestData
