#include <string_view>

namespace TestData {

constexpr std::string_view SEQ_1_TEST = "module graph_0(\n"
                                        "\tclk, data, \n"
                                        "\tres\n"
                                        ");\n"
                                        "\t// Writing inputs\n"
                                        "\tinput clk, data;\n"
                                        "\t// Writing outputs\n"
                                        "\toutput res;\n"
                                        "\t// Writing registers\n"
                                        "\treg q;\n\t\n"
                                        "\talways @(posedge clk) begin\n"
                                        "\t\tq <= data;\n"
                                        "\tend\n\n"
                                        "\tassign res = q;\n"
                                        "endmodule\n";

constexpr std::string_view SEQ_2_TEST =
    "module graph_0(\n"
    "\ten, data, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput en, data;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// EN signal \"en\""
    " - when it is in a logical one state, trigger writes data to the output\n"
    "\talways @(*) begin\n"
    "\t\tif (en) q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";


constexpr std::string_view SEQ_3_TEST =
    "module graph_0(\n"
    "\ten, data, rst, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput en, data, rst;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// RST signal \"rst\""
    " - when it is in a logical zero state, trigger writes logical zero to the output\n"
    "\t// EN signal \"en\""
    " - when it is in a logical one state, trigger writes data to the output\n"
    "\talways @(*) begin\n"
    "\t\tif (!rst) q <= 1'b0;\n"
    "\t\telse if (en) q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";

constexpr std::string_view SEQ_4_TEST =
    "module graph_0(\n"
    "\ten, data, clr, set, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput en, data, clr, set;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// CLR signal \"clr\""
    " - when it is in a logical one state, trigger writes logical zero to the output\n"
    "\t// SET signal \"set\""
    " - when it is in a logical one state, trigger writes logical one to the output\n"
    "\t// EN signal \"en\""
    " - when it is in a logical one state, trigger writes data to the output\n"
    "\talways @(*) begin\n"
    "\t\tif (clr) q <= 1'b0;\n"
    "\t\telse if (set) q <= 1'b1;\n"
    "\t\telse if (en) q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";

constexpr std::string_view SEQ_5_TEST =
    "module graph_0(\n"
    "\tclk, data, rst, set, en, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput clk, data, rst, set, en;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// RST signal \"rst\" - when it is in a logical zero state, trigger "
    "writes logical zero to the output\n"
    "\t// SET signal \"set\" - when it is in a logical one state, trigger "
    "writes logical one to the output\n"
    "\t// EN signal \"en\" - when it is in a logical one state, trigger writes "
    "data to the output\n"
    "\talways @(posedge clk) begin\n"
    "\t\tif (!rst) q <= 1'b0;\n"
    "\t\telse if (set) q <= 1'b1;\n"
    "\t\telse if (en) q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";

constexpr std::string_view SEQ_6_TEST =
    "module graph_0(\n"
    "\tclk, data, rst_n, set, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput clk, data, rst_n, set;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// RST signal \"rst_n\" - when it is in a logical zero state, trigger "
    "writes logical zero to the output\n"
    "\t// RST signal \"rst_n\" is async - always block enables on negedge of RST\n"
    "\t// SET signal \"set\" - when it is in a logical one state, trigger "
    "writes logical one to the output\n"
    "\talways @(negedge clk or negedge rst_n) begin\n"
    "\t\tif (!rst_n) q <= 1'b0;\n"
    "\t\telse if (set) q <= 1'b1;\n"
    "\t\telse q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";


constexpr std::string_view SEQ_7_TEST =
    "module graph_0(\n"
    "\tclk, data, rst_n, en, \n"
    "\tres\n"
    ");\n"
    "\t// Writing inputs\n"
    "\tinput clk, data, rst_n, en;\n"
    "\t// Writing outputs\n"
    "\toutput res;\n"
    "\t// Writing registers\n"
    "\treg q;\n\t\n"
    "\t// RST signal \"rst_n\" - when it is in a logical zero state, trigger "
    "writes logical zero to the output\n"
    "\t// RST signal \"rst_n\" is async - always block enables on negedge of RST\n"
    "\t// EN signal \"en\" - when it is in a logical one state, trigger writes "
    "data to the output\n"
    "\talways @(posedge clk or negedge rst_n) begin\n"
    "\t\tif (!rst_n) q <= 1'b0;\n"
    "\t\telse if (en) q <= data;\n"
    "\tend\n\n"
    "\tassign res = q;\n"
    "endmodule\n";

} // namespace TestData
