#include <CircuitGenGraph/TestbenchGenerator.hpp>

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <iomanip>
#include <iostream>
#include <regex>
#include <sstream>

#ifdef LOGFLAG
#include "easyloggingpp/easylogging++.h"
#endif

namespace CG_Graph {

// ==================== Конструктор ====================

TestbenchGenerator::TestbenchGenerator(GraphPtr i_graph,
                                       const TestbenchConfig &i_config)
    : d_graph(std::move(i_graph)), d_config(i_config) {
  if (!d_graph) {
    throw std::invalid_argument("TestbenchGenerator: graph cannot be null");
  }

  // Собираем имена входов
  auto vertices = d_graph->getBaseVertexes();
  for (auto *input : vertices[VertexTypes::input]) {
    d_inputNames.push_back(std::string(input->getRawName()));
  }

  // Собираем имена выходов
  for (auto *output : vertices[VertexTypes::output]) {
    d_outputNames.push_back(std::string(output->getRawName()));
  }

  // Проверяем наличие последовательностных элементов
  d_hasSequential = !vertices[VertexTypes::sequential].empty();

#ifdef LOGFLAG
  LOG(INFO) << "TestbenchGenerator: initialized for graph '"
            << d_graph->getName() << "' with "
            << d_inputNames.size() << " inputs and "
            << d_outputNames.size() << " outputs";
#endif
}

// ==================== Генерация тестовых векторов ====================

size_t TestbenchGenerator::generateExhaustiveVectors() {
  size_t numInputs = d_inputNames.size();

  if (numInputs > 20) {
#ifdef LOGFLAG
    LOG(WARNING) << "TestbenchGenerator: exhaustive generation for "
                 << numInputs << " inputs will create "
                 << (1ULL << numInputs)
                 << " test vectors. Consider using random vectors.";
#else
    std::cerr << "Warning: exhaustive generation for " << numInputs
              << " inputs will create " << (1ULL << numInputs)
              << " test vectors." << std::endl;
#endif
  }

  d_testVectors.clear();
  uint64_t totalCombinations = 1ULL << numInputs;

  for (uint64_t i = 0; i < totalCombinations; ++i) {
    std::vector<char> inputs(numInputs);
    for (size_t bit = 0; bit < numInputs; ++bit) {
      inputs[bit] = ((i >> bit) & 1) ? '1' : '0';
    }
    std::vector<char> expected = computeExpectedOutputs(inputs);
    d_testVectors.push_back({inputs, expected, {}, false});
  }

#ifdef LOGFLAG
  LOG(INFO) << "TestbenchGenerator: generated " << d_testVectors.size()
            << " exhaustive test vectors";
#endif

  return d_testVectors.size();
}

size_t TestbenchGenerator::generateRandomVectors(size_t i_count,
                                                  uint32_t i_seed) {
  size_t numInputs = d_inputNames.size();

  std::mt19937 gen;
  if (i_seed == 0) {
    std::random_device rd;
    gen.seed(rd());
  } else {
    gen.seed(i_seed);
  }
  std::uniform_int_distribution<> dist(0, 1);

  for (size_t i = 0; i < i_count; ++i) {
    std::vector<char> inputs(numInputs);
    for (size_t bit = 0; bit < numInputs; ++bit) {
      inputs[bit] = dist(gen) ? '1' : '0';
    }
    std::vector<char> expected = computeExpectedOutputs(inputs);
    d_testVectors.push_back({inputs, expected, {}, false});
  }

#ifdef LOGFLAG
  LOG(INFO) << "TestbenchGenerator: generated " << i_count
            << " random test vectors";
#endif

  return i_count;
}

void TestbenchGenerator::addTestVector(const std::vector<char> &i_inputs,
                                        const std::vector<char> &i_expected) {
  if (i_inputs.size() != d_inputNames.size()) {
    throw std::invalid_argument(
        "TestbenchGenerator: input vector size mismatch");
  }

  std::vector<char> expected = i_expected;
  if (expected.empty()) {
    expected = computeExpectedOutputs(i_inputs);
  } else if (expected.size() != d_outputNames.size()) {
    throw std::invalid_argument(
        "TestbenchGenerator: expected output vector size mismatch");
  }

  d_testVectors.push_back({i_inputs, expected, {}, false});
}

void TestbenchGenerator::clearTestVectors() { d_testVectors.clear(); }

// ==================== Генерация тестбенча ====================

std::string TestbenchGenerator::generateHeader() const {
  std::ostringstream ss;
  auto t = std::time(nullptr);
  auto tm = *std::localtime(&t);

  ss << "//=============================================================\n";
  ss << "// Testbench generated by CircuitGen_Graph TestbenchGenerator\n";
  ss << "// Generated at: " << std::put_time(&tm, "%d-%m-%Y %H:%M:%S") << "\n";
  ss << "// Module under test: " << d_graph->getName() << "\n";
  ss << "// Number of test vectors: " << d_testVectors.size() << "\n";
  ss << "//=============================================================\n\n";

  ss << "`timescale " << d_config.timescale << "\n\n";

  return ss.str();
}

std::string TestbenchGenerator::generateSignalDeclarations() const {
  std::ostringstream ss;

  // Входные регистры
  ss << "  // Input signals (directly driven in combinational testbench)\n";
  for (const auto &name : d_inputNames) {
    ss << "  reg " << name << ";\n";
  }
  ss << "\n";

  // Выходные провода
  ss << "  // Output signals\n";
  for (const auto &name : d_outputNames) {
    ss << "  wire " << name << "_dut;\n";
  }
  ss << "\n";

  // Переменные для тестирования
  ss << "  // Test control variables\n";
  ss << "  integer test_num;\n";
  ss << "  integer errors;\n";
  ss << "  integer passed;\n";
  ss << "\n";

  return ss.str();
}

std::string TestbenchGenerator::generateDUTInstantiation() const {
  std::ostringstream ss;

  ss << "  // Device Under Test instantiation\n";
  ss << "  " << d_graph->getName() << " dut (\n";

  // Входы
  for (size_t i = 0; i < d_inputNames.size(); ++i) {
    ss << "    ." << d_inputNames[i] << "(" << d_inputNames[i] << ")";
    if (i < d_inputNames.size() - 1 || !d_outputNames.empty()) {
      ss << ",";
    }
    ss << "\n";
  }

  // Выходы
  for (size_t i = 0; i < d_outputNames.size(); ++i) {
    ss << "    ." << d_outputNames[i] << "(" << d_outputNames[i] << "_dut)";
    if (i < d_outputNames.size() - 1) {
      ss << ",";
    }
    ss << "\n";
  }

  ss << "  );\n\n";

  return ss.str();
}

std::string TestbenchGenerator::generateVCDDump() const {
  if (!d_config.generateVCD) {
    return "";
  }

  std::ostringstream ss;

  ss << "  // VCD dump for waveform viewing\n";
  ss << "  initial begin\n";
  ss << "    $dumpfile(\"" << d_config.vcdFilename << "\");\n";
  ss << "    $dumpvars(0, " << d_graph->getName() << "_tb);\n";
  ss << "  end\n\n";

  return ss.str();
}

std::string TestbenchGenerator::generateStimulusBlock() const {
  std::ostringstream ss;

  ss << "  // Main test block\n";
  ss << "  initial begin\n";
  ss << "    // Initialize\n";
  ss << "    errors = 0;\n";
  ss << "    passed = 0;\n";
  ss << "    test_num = 0;\n";
  ss << "\n";

  // Инициализация всех входов
  for (const auto &name : d_inputNames) {
    ss << "    " << name << " = 1'b0;\n";
  }
  ss << "\n";

  ss << "    $display(\"========================================\");\n";
  ss << "    $display(\"Starting testbench for " << d_graph->getName()
     << "\");\n";
  ss << "    $display(\"Total tests: " << d_testVectors.size() << "\");\n";
  ss << "    $display(\"========================================\");\n";
  ss << "\n";

  ss << "    #" << d_config.resetDuration << ";\n";
  ss << "\n";

  // Генерируем тестовые векторы
  for (size_t i = 0; i < d_testVectors.size(); ++i) {
    const auto &tv = d_testVectors[i];

    ss << "    // Test vector " << i << "\n";
    ss << "    test_num = " << i << ";\n";

    // Устанавливаем входы
    for (size_t j = 0; j < d_inputNames.size(); ++j) {
      ss << "    " << d_inputNames[j] << " = 1'b" << tv.inputs[j] << ";\n";
    }

    ss << "    #" << d_config.stimulusDelay << ";\n";

    // Проверяем выходы
    ss << "    // Expected outputs: ";
    for (size_t j = 0; j < tv.expected.size(); ++j) {
      ss << d_outputNames[j] << "=" << tv.expected[j];
      if (j < tv.expected.size() - 1)
        ss << ", ";
    }
    ss << "\n";

    // Формируем проверку
    ss << "    if (";
    for (size_t j = 0; j < d_outputNames.size(); ++j) {
      ss << d_outputNames[j] << "_dut === 1'b" << tv.expected[j];
      if (j < d_outputNames.size() - 1) {
        ss << " && ";
      }
    }
    ss << ") begin\n";
    ss << "      passed = passed + 1;\n";
    ss << "      $display(\"PASS: Test %0d\", test_num);\n";
    ss << "    end else begin\n";
    ss << "      errors = errors + 1;\n";
    ss << "      $display(\"FAIL: Test %0d\", test_num);\n";
    ss << "      $display(\"  Inputs: ";
    for (size_t j = 0; j < d_inputNames.size(); ++j) {
      ss << d_inputNames[j] << "=%b";
      if (j < d_inputNames.size() - 1)
        ss << ", ";
    }
    ss << "\", ";
    for (size_t j = 0; j < d_inputNames.size(); ++j) {
      ss << d_inputNames[j];
      if (j < d_inputNames.size() - 1)
        ss << ", ";
    }
    ss << ");\n";

    ss << "      $display(\"  Expected: ";
    for (size_t j = 0; j < d_outputNames.size(); ++j) {
      ss << d_outputNames[j] << "=%b";
      if (j < d_outputNames.size() - 1)
        ss << ", ";
    }
    ss << "\", ";
    for (size_t j = 0; j < d_outputNames.size(); ++j) {
      ss << "1'b" << tv.expected[j];
      if (j < d_outputNames.size() - 1)
        ss << ", ";
    }
    ss << ");\n";

    ss << "      $display(\"  Actual:   ";
    for (size_t j = 0; j < d_outputNames.size(); ++j) {
      ss << d_outputNames[j] << "=%b";
      if (j < d_outputNames.size() - 1)
        ss << ", ";
    }
    ss << "\", ";
    for (size_t j = 0; j < d_outputNames.size(); ++j) {
      ss << d_outputNames[j] << "_dut";
      if (j < d_outputNames.size() - 1)
        ss << ", ";
    }
    ss << ");\n";

    ss << "    end\n";
    ss << "\n";
  }

  // Итоговый отчёт
  ss << "    // Final report\n";
  ss << "    $display(\"========================================\");\n";
  ss << "    $display(\"Test Summary:\");\n";
  ss << "    $display(\"  Total:  %0d\", " << d_testVectors.size() << ");\n";
  ss << "    $display(\"  Passed: %0d\", passed);\n";
  ss << "    $display(\"  Failed: %0d\", errors);\n";
  ss << "    if (errors == 0) begin\n";
  ss << "      $display(\"STATUS: ALL TESTS PASSED\");\n";
  ss << "    end else begin\n";
  ss << "      $display(\"STATUS: SOME TESTS FAILED\");\n";
  ss << "    end\n";
  ss << "    $display(\"========================================\");\n";
  ss << "\n";
  ss << "    $finish;\n";
  ss << "  end\n";

  return ss.str();
}

std::string TestbenchGenerator::generateCheckBlock() const {
  // Для комбинационных схем проверка встроена в stimulus block
  // Для последовательностных схем можно добавить отдельный блок
  return "";
}

std::string TestbenchGenerator::getTestbenchCode() const {
  std::ostringstream ss;

  ss << generateHeader();
  ss << "module " << d_graph->getName() << "_tb;\n\n";
  ss << generateSignalDeclarations();
  ss << generateDUTInstantiation();
  ss << generateVCDDump();
  ss << generateStimulusBlock();
  ss << generateCheckBlock();
  ss << "\nendmodule\n";

  return ss.str();
}

bool TestbenchGenerator::toVerilogTestbench(const std::string &i_path,
                                             const std::string &i_filename) {
  if (d_testVectors.empty()) {
#ifdef LOGFLAG
    LOG(WARNING) << "TestbenchGenerator: no test vectors to generate testbench";
#else
    std::cerr << "Warning: no test vectors to generate testbench" << std::endl;
#endif
    return false;
  }

  std::string filename = i_filename.empty()
                             ? (d_graph->getName() + "_tb.v")
                             : (i_filename + ".v");

  std::filesystem::create_directories(i_path);
  std::string fullPath = i_path + "/" + filename;

  std::ofstream file(fullPath);
  if (!file) {
#ifdef LOGFLAG
    LOG(ERROR) << "TestbenchGenerator: cannot create file " << fullPath;
#else
    std::cerr << "Error: cannot create file " << fullPath << std::endl;
#endif
    return false;
  }

  file << getTestbenchCode();
  file.close();

#ifdef LOGFLAG
  LOG(INFO) << "TestbenchGenerator: testbench written to " << fullPath;
#endif

  return true;
}

// ==================== Симуляция и верификация ====================

std::vector<char>
TestbenchGenerator::computeExpectedOutputs(const std::vector<char> &i_inputs) {
  // Используем встроенный симулятор графа
  // graphSimulation принимает вектор по значению,
  // поэтому копирование происходит автоматически
  std::vector<char> outputs = d_graph->graphSimulation(i_inputs);
  d_graph->simulationRemove();
  return outputs;
}

VerificationResult TestbenchGenerator::runInternalSimulation() {
  VerificationResult result;
  result.totalTests = d_testVectors.size();

  for (auto &tv : d_testVectors) {
    // Пересчитываем expected, если содержит 'x' (неопределённые значения)
    bool hasUndefined = false;
    for (char c : tv.expected) {
      if (c == 'x' || c == 'X' || c == 'z' || c == 'Z') {
        hasUndefined = true;
        break;
      }
    }
    if (hasUndefined || tv.expected.empty()) {
      tv.expected = computeExpectedOutputs(tv.inputs);
    }
    
    tv.actual = computeExpectedOutputs(tv.inputs);
    tv.passed = (tv.actual == tv.expected);

    if (tv.passed) {
      ++result.passedTests;
    } else {
      ++result.failedTests;
    }
  }

  result.vectors = d_testVectors;
  result.success = (result.failedTests == 0);

#ifdef LOGFLAG
  LOG(INFO) << "TestbenchGenerator: internal simulation completed. "
            << result.passedTests << "/" << result.totalTests << " passed";
#endif

  return result;
}

std::pair<int, std::string>
TestbenchGenerator::executeCommand(const std::string &i_command) {
  std::array<char, 4096> buffer;
  std::string output;

  // Добавляем перенаправление stderr в stdout
  std::string fullCommand = i_command + " 2>&1";

  FILE *pipe = popen(fullCommand.c_str(), "r");
  if (!pipe) {
    return {-1, "Failed to execute command"};
  }

  while (fgets(buffer.data(), buffer.size(), pipe) != nullptr) {
    output += buffer.data();
  }

  int exitCode = pclose(pipe);

#ifdef _WIN32
  // Windows возвращает код напрямую
#else
  // Unix-подобные системы: извлекаем код возврата
  if (WIFEXITED(exitCode)) {
    exitCode = WEXITSTATUS(exitCode);
  }
#endif

  return {exitCode, output};
}

bool TestbenchGenerator::isIcarusAvailable(const std::string &i_icarusPath) {
  std::string command = i_icarusPath + " -V 2>&1";
  FILE *pipe = popen(command.c_str(), "r");
  if (!pipe) {
    return false;
  }
  // Читаем и игнорируем вывод
  char buffer[128];
  while (fgets(buffer, sizeof(buffer), pipe) != nullptr) {
    // Просто игнорируем
  }
  int exitCode = pclose(pipe);
#ifndef _WIN32
  if (WIFEXITED(exitCode)) {
    exitCode = WEXITSTATUS(exitCode);
  }
#endif
  return (exitCode == 0);
}

VerificationResult
TestbenchGenerator::runIcarusVerification(const std::string &i_workDir,
                                           const std::string &i_icarusPath,
                                           const std::string &i_vvpPath) {
  VerificationResult result;

  // Проверяем наличие Icarus Verilog
  if (!isIcarusAvailable(i_icarusPath)) {
    result.success = false;
    result.errorMessage = "Icarus Verilog not found. Please install it with: "
                          "sudo apt install iverilog";
#ifdef LOGFLAG
    LOG(ERROR) << "TestbenchGenerator: " << result.errorMessage;
#else
    std::cerr << "Error: " << result.errorMessage << std::endl;
#endif
    return result;
  }

  // Создаём рабочую директорию
  std::filesystem::create_directories(i_workDir);
  std::filesystem::create_directories(i_workDir + "/submodules");

  // Генерируем Verilog файл модуля
  if (!d_graph->toVerilog(i_workDir, d_graph->getName() + ".v")) {
    result.success = false;
    result.errorMessage = "Failed to generate Verilog module";
    return result;
  }

  // Генерируем тестбенч
  if (!toVerilogTestbench(i_workDir)) {
    result.success = false;
    result.errorMessage = "Failed to generate testbench";
    return result;
  }

  std::string modulePath = i_workDir + "/" + d_graph->getName() + ".v";
  std::string tbPath = i_workDir + "/" + d_graph->getName() + "_tb.v";
  std::string outPath = i_workDir + "/" + d_graph->getName() + "_sim";
  std::string submodulesPath = i_workDir + "/submodules";

  // Собираем список всех подмодулей
  std::string submoduleFiles;
  if (std::filesystem::exists(submodulesPath)) {
    for (const auto &entry :
         std::filesystem::directory_iterator(submodulesPath)) {
      if (entry.path().extension() == ".v") {
        submoduleFiles += " " + entry.path().string();
      }
    }
  }

  // Компилируем с Icarus Verilog (подавляем информационный вывод)
  std::string compileCmd = i_icarusPath + " -o " + outPath + " " + modulePath +
                           " " + tbPath + submoduleFiles + " 2>&1";

#ifdef LOGFLAG
  LOG(INFO) << "TestbenchGenerator: compiling with command: " << compileCmd;
#endif

  auto [compileExitCode, compileOutput] = executeCommand(compileCmd);

  // Фильтруем вывод - убираем copyright/version информацию
  std::string filteredOutput;
  std::istringstream iss(compileOutput);
  std::string line;
  bool inCopyright = false;
  while (std::getline(iss, line)) {
    // Пропускаем строки с Copyright, version, лицензией
    if (line.find("Copyright") != std::string::npos ||
        line.find("version") != std::string::npos ||
        line.find("This program is free software") != std::string::npos ||
        line.find("General Public License") != std::string::npos ||
        line.find("FLAGS DLL") != std::string::npos ||
        line.find("WITHOUT ANY WARRANTY") != std::string::npos ||
        line.find("51 Franklin Street") != std::string::npos) {
      inCopyright = true;
      continue;
    }
    // Пропускаем пустые строки после copyright
    if (inCopyright && line.empty()) {
      continue;
    }
    inCopyright = false;
    // Добавляем только значимые строки (ошибки, предупреждения)
    if (!line.empty()) {
      filteredOutput += line + "\n";
    }
  }

  if (compileExitCode != 0) {
    result.success = false;
    result.simulatorExitCode = compileExitCode;
    result.simulatorOutput =
        filteredOutput.empty() ? compileOutput : filteredOutput;
    result.errorMessage = "Compilation failed";
#ifdef LOGFLAG
    LOG(ERROR) << "TestbenchGenerator: compilation failed: " << compileOutput;
#else
    std::cerr << "Compilation error: " << compileOutput << std::endl;
#endif
    return result;
  }

  // Запускаем симуляцию
  std::string simCmd = i_vvpPath + " " + outPath;

#ifdef LOGFLAG
  LOG(INFO) << "TestbenchGenerator: running simulation: " << simCmd;
#endif

  auto [simExitCode, simOutput] = executeCommand(simCmd);

  result.simulatorExitCode = simExitCode;
  result.simulatorOutput = simOutput;

  // Парсим результаты
  result.totalTests = d_testVectors.size();

  // Ищем строки PASS/FAIL в выводе
  std::regex passRegex(R"(PASS:\s*Test\s*(\d+))");
  std::regex failRegex(R"(FAIL:\s*Test\s*(\d+))");
  std::regex statusRegex(R"(STATUS:\s*(ALL TESTS PASSED|SOME TESTS FAILED))");

  std::smatch match;
  std::string::const_iterator searchStart(simOutput.cbegin());

  while (std::regex_search(searchStart, simOutput.cend(), match, passRegex)) {
    ++result.passedTests;
    searchStart = match.suffix().first;
  }

  searchStart = simOutput.cbegin();
  while (std::regex_search(searchStart, simOutput.cend(), match, failRegex)) {
    ++result.failedTests;
    searchStart = match.suffix().first;
  }

  if (std::regex_search(simOutput, match, statusRegex)) {
    result.success = (match[1].str() == "ALL TESTS PASSED");
  } else {
    // Если статус не найден, определяем по количеству ошибок
    result.success = (result.failedTests == 0);
  }

#ifdef LOGFLAG
  LOG(INFO) << "TestbenchGenerator: Icarus verification completed. "
            << result.passedTests << "/" << result.totalTests << " passed";
#endif

  if (d_config.verbose) {
    std::cout << simOutput << std::endl;
  }

  return result;
}

VerificationResult
TestbenchGenerator::compareSimulations(const std::string &i_workDir) {
  VerificationResult result;

  // Запускаем внутреннюю симуляцию
  auto internalResult = runInternalSimulation();

  // Запускаем Icarus верификацию
  auto icarusResult = runIcarusVerification(i_workDir);

  // Сравниваем результаты
  result.totalTests = d_testVectors.size();
  result.passedTests = 0;
  result.failedTests = 0;

  if (internalResult.passedTests == icarusResult.passedTests) {
    result.success = true;
    result.passedTests = internalResult.passedTests;
    result.failedTests = internalResult.failedTests;
  } else {
    result.success = false;
    result.errorMessage = "Internal and Icarus simulation results differ";
  }

  result.simulatorOutput = icarusResult.simulatorOutput;
  result.simulatorExitCode = icarusResult.simulatorExitCode;

  return result;
}

// ==================== Утилиты ====================

std::string
TestbenchGenerator::toVerilogLiteral(const std::vector<char> &i_values) {
  std::ostringstream ss;
  ss << i_values.size() << "'b";
  for (auto it = i_values.rbegin(); it != i_values.rend(); ++it) {
    ss << *it;
  }
  return ss.str();
}

std::vector<std::vector<char>>
TestbenchGenerator::parseIcarusOutput(const std::string &i_output) {
  std::vector<std::vector<char>> results;

  // Парсинг вывода для извлечения фактических значений
  // Формат: "Actual: out1=X, out2=Y, ..."
  std::regex actualRegex(R"(Actual:\s*(.+))");
  std::smatch match;

  std::string::const_iterator searchStart(i_output.cbegin());
  while (
      std::regex_search(searchStart, i_output.cend(), match, actualRegex)) {
    std::string actualStr = match[1].str();
    std::vector<char> values;

    std::regex valueRegex(R"(\w+\s*=\s*([01xzXZ]))");
    std::smatch valueMatch;
    std::string::const_iterator actualSearchStart(actualStr.cbegin());

    while (std::regex_search(actualSearchStart, actualStr.cend(), valueMatch,
                             valueRegex)) {
      char val = valueMatch[1].str()[0];
      values.push_back(val);
      actualSearchStart = valueMatch.suffix().first;
    }

    if (!values.empty()) {
      results.push_back(values);
    }

    searchStart = match.suffix().first;
  }

  return results;
}

} // namespace CG_Graph
