#include "CircuitGenGraph/TestbenchGenerator.hpp"
#include "CircuitGenGraph/GraphVertex.hpp"

#include <CircuitGenGraph/Logging.hpp>

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <iomanip>
#include <fstream>
#include <iostream>
#include <regex>
#include <set>
#include <sstream>

#ifndef _WIN32
#include <fcntl.h>
#include <sys/wait.h>
#include <unistd.h>
#endif

namespace CG_Graph {

// --- Конструктор ---

TestbenchGenerator::TestbenchGenerator(GraphPtr i_graph,
                                       const TestbenchConfig &i_config) :
    d_graph(std::move(i_graph)), d_config(i_config) {
  if (!d_graph) {
    throw std::invalid_argument("TestbenchGenerator: graph cannot be null");
  }

  // Собираем имена входов
  auto vertices = d_graph->getBaseVertexes();
  for (auto *input: vertices[VertexTypes::input]) {
    d_inputNames.push_back(std::string(input->getRawName()));
  }

  // Собираем имена выходов
  for (auto *output: vertices[VertexTypes::output]) {
    d_outputNames.push_back(std::string(output->getRawName()));
  }

  // Проверяем наличие последовательностных элементов
  d_hasSequential = !vertices[VertexTypes::sequential].empty();

  // Detect clock/reset signals for sequential circuits
  if (d_hasSequential) {
    detectClockSignals();
  } else {
    d_dataInputNames = d_inputNames;
  }

  CG_LOG_INFO << "TestbenchGenerator: initialized for graph '"
              << d_graph->getName() << "' with " << d_inputNames.size()
              << " inputs and " << d_outputNames.size() << " outputs";
}

// --- Генерация тестовых векторов ---

size_t TestbenchGenerator::generateExhaustiveVectors() {
  size_t numInputs = d_inputNames.size();

  if (numInputs > 20) {
    CG_LOG_WARNING << "TestbenchGenerator: exhaustive generation for "
                   << numInputs << " inputs will create " << (1ULL << numInputs)
                   << " test vectors. Consider using random vectors.";
  }

  d_testVectors.clear();
  uint64_t totalCombinations = 1ULL << numInputs;

  for (uint64_t i = 0; i < totalCombinations; ++i) {
    std::vector<char> inputs(numInputs);
    for (size_t bit = 0; bit < numInputs; ++bit) {
      inputs[bit] = ((i >> bit) & 1) ? '1' : '0';
    }
    std::vector<char> expected = computeExpectedOutputs(inputs);
    d_testVectors.push_back({inputs, expected, {}, false});
  }

  CG_LOG_INFO << "TestbenchGenerator: generated " << d_testVectors.size()
              << " exhaustive test vectors";

  return d_testVectors.size();
}

size_t TestbenchGenerator::generateRandomVectors(size_t i_count,
                                                 uint32_t i_seed) {
  size_t numInputs = d_inputNames.size();

  std::mt19937 gen;
  if (i_seed == 0) {
    std::random_device rd;
    gen.seed(rd());
  } else {
    gen.seed(i_seed);
  }
  std::uniform_int_distribution<> dist(0, 1);

  for (size_t i = 0; i < i_count; ++i) {
    std::vector<char> inputs(numInputs);
    for (size_t bit = 0; bit < numInputs; ++bit) {
      inputs[bit] = dist(gen) ? '1' : '0';
    }
    std::vector<char> expected = computeExpectedOutputs(inputs);
    d_testVectors.push_back({inputs, expected, {}, false});
  }

  CG_LOG_INFO << "TestbenchGenerator: generated " << i_count
              << " random test vectors";

  return i_count;
}

void TestbenchGenerator::addTestVector(const std::vector<char> &i_inputs,
                                       const std::vector<char> &i_expected) {
  if (i_inputs.size() != d_inputNames.size()) {
    throw std::invalid_argument(
        "TestbenchGenerator: input vector size mismatch");
  }

  std::vector<char> expected = i_expected;
  if (expected.empty()) {
    expected = computeExpectedOutputs(i_inputs);
  } else if (expected.size() != d_outputNames.size()) {
    throw std::invalid_argument(
        "TestbenchGenerator: expected output vector size mismatch");
  }

  d_testVectors.push_back({i_inputs, expected, {}, false});
}

void TestbenchGenerator::clearTestVectors() {
  d_testVectors.clear();
}

// --- Генерация тестбенча ---

std::string TestbenchGenerator::generateHeader() const {
  std::ostringstream ss;
  auto t = std::time(nullptr);
  auto tm = *std::localtime(&t);

  ss << "//=============================================================\n";
  ss << "// Testbench generated by CircuitGen_Graph TestbenchGenerator\n";
  ss << "// Generated at: " << std::put_time(&tm, "%d-%m-%Y %H:%M:%S") << "\n";
  ss << "// Module under test: " << d_graph->getName() << "\n";
  const size_t vectorCount =
      d_hasSequential ? d_seqTestVectors.size() : d_testVectors.size();
  ss << "// Number of test vectors: " << vectorCount << "\n";
  ss << "//=============================================================\n\n";

  ss << "`timescale " << d_config.timescale << "\n\n";

  return ss.str();
}

std::string TestbenchGenerator::generateSignalDeclarations() const {
  std::ostringstream ss;

  // Входные регистры
  ss << "  // Input signals (directly driven in combinational testbench)\n";
  for (const auto &name: d_inputNames) {
    ss << "  reg " << name << ";\n";
  }
  ss << "\n";

  // Выходные провода
  ss << "  // Output signals\n";
  for (const auto &name: d_outputNames) {
    ss << "  wire " << name << "_dut;\n";
  }
  ss << "\n";

  // Переменные для тестирования
  ss << "  // Test control variables\n";
  ss << "  integer test_num;\n";
  ss << "  integer errors;\n";
  ss << "  integer passed;\n";
  ss << "\n";

  return ss.str();
}

std::string TestbenchGenerator::generateDUTInstantiation() const {
  std::ostringstream ss;

  ss << "  // Device Under Test instantiation\n";
  ss << "  " << d_graph->getName() << " dut (\n";

  // Входы
  for (size_t i = 0; i < d_inputNames.size(); ++i) {
    ss << "    ." << d_inputNames[i] << "(" << d_inputNames[i] << ")";
    if (i < d_inputNames.size() - 1 || !d_outputNames.empty()) {
      ss << ",";
    }
    ss << "\n";
  }

  // Выходы
  for (size_t i = 0; i < d_outputNames.size(); ++i) {
    ss << "    ." << d_outputNames[i] << "(" << d_outputNames[i] << "_dut)";
    if (i < d_outputNames.size() - 1) {
      ss << ",";
    }
    ss << "\n";
  }

  ss << "  );\n\n";

  return ss.str();
}

std::string TestbenchGenerator::generateVCDDump() const {
  if (!d_config.generateVCD) {
    return "";
  }

  std::ostringstream ss;

  ss << "  // VCD dump for waveform viewing\n";
  ss << "  initial begin\n";
  ss << "    $dumpfile(\"" << d_config.vcdFilename << "\");\n";
  ss << "    $dumpvars(0, " << d_graph->getName() << "_tb);\n";
  ss << "  end\n\n";

  return ss.str();
}

std::string TestbenchGenerator::generateStimulusBlock() const {
  std::ostringstream ss;

  ss << "  // Main test block\n";
  ss << "  initial begin\n";
  ss << "    // Initialize\n";
  ss << "    errors = 0;\n";
  ss << "    passed = 0;\n";
  ss << "    test_num = 0;\n";
  ss << "\n";

  // Инициализация всех входов
  for (const auto &name: d_inputNames) {
    ss << "    " << name << " = 1'b0;\n";
  }
  ss << "\n";

  ss << "    $display(\"========================================\");\n";
  ss << "    $display(\"Starting testbench for " << d_graph->getName()
     << "\");\n";
  ss << "    $display(\"Total tests: " << d_testVectors.size() << "\");\n";
  ss << "    $display(\"========================================\");\n";
  ss << "\n";

  ss << "    #" << d_config.resetDuration << ";\n";
  ss << "\n";

  // Генерируем тестовые векторы
  for (size_t i = 0; i < d_testVectors.size(); ++i) {
    const auto &tv = d_testVectors[i];

    ss << "    // Test vector " << i << "\n";
    ss << "    test_num = " << i << ";\n";

    // Устанавливаем входы
    for (size_t j = 0; j < d_inputNames.size(); ++j) {
      ss << "    " << d_inputNames[j] << " = 1'b" << tv.inputs[j] << ";\n";
    }

    ss << "    #" << d_config.stimulusDelay << ";\n";

    // Проверяем выходы
    ss << "    // Expected outputs: ";
    for (size_t j = 0; j < tv.expected.size(); ++j) {
      ss << d_outputNames[j] << "=" << tv.expected[j];
      if (j < tv.expected.size() - 1)
        ss << ", ";
    }
    ss << "\n";

    // Формируем проверку
    ss << "    if (";
    for (size_t j = 0; j < d_outputNames.size(); ++j) {
      ss << d_outputNames[j] << "_dut === 1'b" << tv.expected[j];
      if (j < d_outputNames.size() - 1) {
        ss << " && ";
      }
    }
    ss << ") begin\n";
    ss << "      passed = passed + 1;\n";
    ss << "      $display(\"PASS: Test %0d\", test_num);\n";
    ss << "    end else begin\n";
    ss << "      errors = errors + 1;\n";
    ss << "      $display(\"FAIL: Test %0d\", test_num);\n";
    ss << "      $display(\"  Inputs: ";
    for (size_t j = 0; j < d_inputNames.size(); ++j) {
      ss << d_inputNames[j] << "=%b";
      if (j < d_inputNames.size() - 1)
        ss << ", ";
    }
    ss << "\", ";
    for (size_t j = 0; j < d_inputNames.size(); ++j) {
      ss << d_inputNames[j];
      if (j < d_inputNames.size() - 1)
        ss << ", ";
    }
    ss << ");\n";

    ss << "      $display(\"  Expected: ";
    for (size_t j = 0; j < d_outputNames.size(); ++j) {
      ss << d_outputNames[j] << "=%b";
      if (j < d_outputNames.size() - 1)
        ss << ", ";
    }
    ss << "\", ";
    for (size_t j = 0; j < d_outputNames.size(); ++j) {
      ss << "1'b" << tv.expected[j];
      if (j < d_outputNames.size() - 1)
        ss << ", ";
    }
    ss << ");\n";

    ss << "      $display(\"  Actual:   ";
    for (size_t j = 0; j < d_outputNames.size(); ++j) {
      ss << d_outputNames[j] << "=%b";
      if (j < d_outputNames.size() - 1)
        ss << ", ";
    }
    ss << "\", ";
    for (size_t j = 0; j < d_outputNames.size(); ++j) {
      ss << d_outputNames[j] << "_dut";
      if (j < d_outputNames.size() - 1)
        ss << ", ";
    }
    ss << ");\n";

    ss << "    end\n";
    ss << "\n";
  }

  // Итоговый отчет
  ss << "    // Final report\n";
  ss << "    $display(\"========================================\");\n";
  ss << "    $display(\"Test Summary:\");\n";
  ss << "    $display(\"  Total:  %0d\", " << d_testVectors.size() << ");\n";
  ss << "    $display(\"  Passed: %0d\", passed);\n";
  ss << "    $display(\"  Failed: %0d\", errors);\n";
  ss << "    if (errors == 0) begin\n";
  ss << "      $display(\"STATUS: ALL TESTS PASSED\");\n";
  ss << "    end else begin\n";
  ss << "      $display(\"STATUS: SOME TESTS FAILED\");\n";
  ss << "    end\n";
  ss << "    $display(\"========================================\");\n";
  ss << "\n";
  ss << "    $finish;\n";
  ss << "  end\n";

  return ss.str();
}

std::string TestbenchGenerator::generateCheckBlock() const {
  // Для комбинационных схем проверка встроена в stimulus block
  // Для последовательностных схем можно добавить отдельный блок
  return "";
}

std::string TestbenchGenerator::getTestbenchCode() const {
  std::ostringstream ss;

  ss << generateHeader();
  ss << "module " << d_graph->getName() << "_tb;\n\n";

  if (d_hasSequential) {
    // Последовательностный тестбенч
    ss << generateSequentialSignalDeclarations();
    ss << generateSequentialDUTInstantiation();
    ss << generateVCDDump();
    ss << generateClockBlock();
    ss << generateSequentialStimulusBlock();
  } else {
    // Комбинационный тестбенч
    ss << generateSignalDeclarations();
    ss << generateDUTInstantiation();
    ss << generateVCDDump();
    ss << generateStimulusBlock();
    ss << generateCheckBlock();
  }

  ss << "\nendmodule\n";

  return ss.str();
}

bool TestbenchGenerator::toVerilogTestbench(const std::string &i_path,
                                            const std::string &i_filename) {
  bool hasVectors =
      d_hasSequential ? !d_seqTestVectors.empty() : !d_testVectors.empty();
  if (!hasVectors) {
    CG_LOG_WARNING
        << "TestbenchGenerator: no test vectors to generate testbench";
    return false;
  }

  std::string filename =
      i_filename.empty() ? (d_graph->getName() + "_tb.v") : (i_filename + ".v");

  std::filesystem::create_directories(i_path);
  std::string fullPath = i_path + "/" + filename;

  CG_LOG_INFO << "TestbenchGenerator: generating Verilog testbench at "
              << fullPath;

  std::ofstream file(fullPath);
  if (!file) {
    CG_LOG_ERROR << "TestbenchGenerator: cannot create file " << fullPath;
    return false;
  }

  file << getTestbenchCode();
  file.close();

  const size_t vectorCount =
      d_hasSequential ? d_seqTestVectors.size() : d_testVectors.size();
  CG_LOG_INFO << "TestbenchGenerator: testbench written to " << fullPath
              << " with " << vectorCount << " vectors";

  return true;
}

// --- Симуляция и верификация ---

std::vector<char>
TestbenchGenerator::computeExpectedOutputs(const std::vector<char> &i_inputs) {
  // Используем встроенный симулятор графа
  // graphSimulation принимает вектор по значению,
  // поэтому копирование происходит автоматически
  std::vector<char> outputs = d_graph->graphSimulation(i_inputs);
  d_graph->simulationRemove();
  return outputs;
}

VerificationResult TestbenchGenerator::runInternalSimulation() {
  VerificationResult result;

  // Внутренняя симуляция (graphSimulation) работает только для
  // комбинационных схем — она не моделирует состояние регистров
  if (d_hasSequential) {
    result.success = false;
    result.errorMessage =
        "Internal simulation is not supported for sequential circuits. "
        "Use runIcarusVerification() instead.";
    return result;
  }

  result.totalTests = d_testVectors.size();

  for (auto &tv: d_testVectors) {
    // Пересчитываем expected, если содержит 'x' (неопределенные значения)
    bool hasUndefined = false;
    for (char c: tv.expected) {
      if (c == 'x' || c == 'X' || c == 'z' || c == 'Z') {
        hasUndefined = true;
        break;
      }
    }
    if (hasUndefined || tv.expected.empty()) {
      tv.expected = computeExpectedOutputs(tv.inputs);
    }

    tv.actual = computeExpectedOutputs(tv.inputs);
    tv.passed = (tv.actual == tv.expected);

    if (tv.passed) {
      ++result.passedTests;
    } else {
      ++result.failedTests;
    }
  }

  result.vectors = d_testVectors;
  result.success = (result.failedTests == 0);

  CG_LOG_INFO << "TestbenchGenerator: internal simulation completed. "
              << result.passedTests << "/" << result.totalTests << " passed";

  return result;
}

std::pair<int, std::string>
TestbenchGenerator::executeCommandSafe(const std::vector<std::string> &i_argv) {
  if (i_argv.empty()) {
    return {-1, "Empty command"};
  }

#ifdef _WIN32
  // На Windows используем старый метод через popen для совместимости
  std::string command = i_argv[0];
  for (size_t i = 1; i < i_argv.size(); ++i) {
    command += " " + i_argv[i];
  }
  return executeCommand(command);
#else
  // Unix: используем fork + execvp для безопасного выполнения
  int pipefd[2];
  if (pipe(pipefd) == -1) {
    return {-1, "Failed to create pipe"};
  }

  pid_t pid = fork();
  if (pid == -1) {
    close(pipefd[0]);
    close(pipefd[1]);
    return {-1, "Failed to fork process"};
  }

  if (pid == 0) {
    // Дочерний процесс
    close(pipefd[0]); // Закрываем читающий конец

    // Перенаправляем stdout и stderr в pipe
    dup2(pipefd[1], STDOUT_FILENO);
    dup2(pipefd[1], STDERR_FILENO);
    close(pipefd[1]);

    // Подготавливаем argv для execvp
    std::vector<char *> argv_c;
    argv_c.reserve(i_argv.size() + 1);
    for (const auto &arg: i_argv) {
      argv_c.push_back(const_cast<char *>(arg.c_str()));
    }
    argv_c.push_back(nullptr);

    // Выполняем команду
    execvp(argv_c[0], argv_c.data());

    // Если execvp вернулся, произошла ошибка
    CG_LOG_ERROR << "Failed to execute: " << i_argv[0];
    _exit(127);
  }

  // Родительский процесс
  close(pipefd[1]); // Закрываем пишущий конец

  // Читаем вывод
  std::string output;
  std::array<char, 4096> buffer;
  ssize_t bytesRead;
  while ((bytesRead = read(pipefd[0], buffer.data(), buffer.size())) > 0) {
    output.append(buffer.data(), bytesRead);
  }
  close(pipefd[0]);

  // Ждем завершения дочернего процесса
  int status;
  waitpid(pid, &status, 0);

  int exitCode = 0;
  if (WIFEXITED(status)) {
    exitCode = WEXITSTATUS(status);
  } else if (WIFSIGNALED(status)) {
    exitCode = 128 + WTERMSIG(status);
  } else {
    exitCode = -1;
  }

  return {exitCode, output};
#endif
}

std::pair<int, std::string>
TestbenchGenerator::executeCommand(const std::string &i_command) {
  std::array<char, 4096> buffer;
  std::string output;

  // Добавляем перенаправление stderr в stdout
  std::string fullCommand = i_command + " 2>&1";

  FILE *pipe = popen(fullCommand.c_str(), "r");
  if (!pipe) {
    return {-1, "Failed to execute command"};
  }

  while (fgets(buffer.data(), buffer.size(), pipe) != nullptr) {
    output += buffer.data();
  }

  int exitCode = pclose(pipe);

#ifdef _WIN32
  // Windows возвращает код напрямую
#else
  // Unix-подобные системы: извлекаем код возврата
  if (WIFEXITED(exitCode)) {
    exitCode = WEXITSTATUS(exitCode);
  }
#endif

  return {exitCode, output};
}

bool TestbenchGenerator::isIcarusAvailable(const std::string &i_icarusPath) {
  std::string command = i_icarusPath + " -V 2>&1";
  FILE *pipe = popen(command.c_str(), "r");
  if (!pipe) {
    return false;
  }
  // Читаем и игнорируем вывод
  char buffer[128];
  while (fgets(buffer, sizeof(buffer), pipe) != nullptr) {
    // Просто игнорируем
  }
  int exitCode = pclose(pipe);
#ifndef _WIN32
  if (WIFEXITED(exitCode)) {
    exitCode = WEXITSTATUS(exitCode);
  }
#endif
  return (exitCode == 0);
}

VerificationResult
TestbenchGenerator::runIcarusVerification(const std::string &i_workDir,
                                          const std::string &i_icarusPath,
                                          const std::string &i_vvpPath) {
  VerificationResult result;

  // Проверяем наличие Icarus Verilog
  if (!isIcarusAvailable(i_icarusPath)) {
    result.success = false;
    result.errorMessage = "Icarus Verilog not found. Please install it with: "
                          "sudo apt install iverilog";
    CG_LOG_ERROR << "TestbenchGenerator: " << result.errorMessage;
    return result;
  }

  // Создаем рабочую директорию
  std::filesystem::create_directories(i_workDir);
  std::filesystem::create_directories(i_workDir + "/submodules");

  // Генерируем Verilog файл модуля
  if (!d_graph->toVerilog(i_workDir, d_graph->getName() + ".v")) {
    result.success = false;
    result.errorMessage = "Failed to generate Verilog module";
    return result;
  }

  // Генерируем тестбенч
  if (!toVerilogTestbench(i_workDir)) {
    result.success = false;
    result.errorMessage = "Failed to generate testbench";
    return result;
  }

  std::string modulePath = i_workDir + "/" + d_graph->getName() + ".v";
  std::string tbPath = i_workDir + "/" + d_graph->getName() + "_tb.v";
  std::string outPath = i_workDir + "/" + d_graph->getName() + "_sim";
  std::string submodulesPath = i_workDir + "/submodules";

  // Собираем список всех подмодулей в вектор
  std::vector<std::string> compileArgs;
  compileArgs.push_back(i_icarusPath);
  compileArgs.push_back("-o");
  compileArgs.push_back(outPath);
  compileArgs.push_back(modulePath);
  compileArgs.push_back(tbPath);

  if (std::filesystem::exists(submodulesPath)) {
    for (const auto &entry:
         std::filesystem::directory_iterator(submodulesPath)) {
      if (entry.path().extension() == ".v") {
        compileArgs.push_back(entry.path().string());
      }
    }
  }

  std::ostringstream cmdLog;
  for (const auto &arg: compileArgs) {
    cmdLog << arg << " ";
  }
  CG_LOG_INFO << "TestbenchGenerator: compiling with command: " << cmdLog.str();

  auto [compileExitCode, compileOutput] = executeCommandSafe(compileArgs);

  // Фильтруем вывод - убираем copyright/version информацию
  std::string filteredOutput;
  std::istringstream iss(compileOutput);
  std::string line;
  bool inCopyright = false;
  while (std::getline(iss, line)) {
    // Пропускаем строки с Copyright, version, лицензией
    if (line.find("Copyright") != std::string::npos ||
        line.find("version") != std::string::npos ||
        line.find("This program is free software") != std::string::npos ||
        line.find("General Public License") != std::string::npos ||
        line.find("FLAGS DLL") != std::string::npos ||
        line.find("WITHOUT ANY WARRANTY") != std::string::npos ||
        line.find("51 Franklin Street") != std::string::npos) {
      inCopyright = true;
      continue;
    }
    // Пропускаем пустые строки после copyright
    if (inCopyright && line.empty()) {
      continue;
    }
    inCopyright = false;
    // Добавляем только значимые строки (ошибки, предупреждения)
    if (!line.empty()) {
      filteredOutput += line + "\n";
    }
  }

  if (compileExitCode != 0) {
    result.success = false;
    result.simulatorExitCode = compileExitCode;
    result.simulatorOutput =
        filteredOutput.empty() ? compileOutput : filteredOutput;
    result.errorMessage = "Compilation failed";
    CG_LOG_ERROR << "TestbenchGenerator: compilation failed: " << compileOutput;
    return result;
  }

  // Запускаем симуляцию
  std::vector<std::string> simArgs = {i_vvpPath, outPath};

  CG_LOG_INFO << "TestbenchGenerator: running simulation: " << i_vvpPath << " "
              << outPath;

  auto [simExitCode, simOutput] = executeCommandSafe(simArgs);

  result.simulatorExitCode = simExitCode;
  result.simulatorOutput = simOutput;

  // Парсим результаты
  result.totalTests =
      d_hasSequential ? d_seqTestVectors.size() : d_testVectors.size();

  // Ищем строки PASS/FAIL в выводе
  std::regex passRegex(R"(PASS:\s*Test\s*(\d+))");
  std::regex failRegex(R"(FAIL:\s*Test\s*(\d+))");
  std::regex statusRegex(R"(STATUS:\s*(ALL TESTS PASSED|SOME TESTS FAILED))");

  std::smatch match;
  std::string::const_iterator searchStart(simOutput.cbegin());

  while (std::regex_search(searchStart, simOutput.cend(), match, passRegex)) {
    ++result.passedTests;
    searchStart = match.suffix().first;
  }

  searchStart = simOutput.cbegin();
  while (std::regex_search(searchStart, simOutput.cend(), match, failRegex)) {
    ++result.failedTests;
    searchStart = match.suffix().first;
  }

  if (std::regex_search(simOutput, match, statusRegex)) {
    result.success =
        (match[1].str() == "ALL TESTS PASSED") && (simExitCode == 0);
  } else {
    // Если статус не найден, определяем по количеству ошибок и коду возврата
    result.success = (result.failedTests == 0) && (simExitCode == 0);
  }

  CG_LOG_INFO << "TestbenchGenerator: Icarus verification completed. "
              << result.passedTests << "/" << result.totalTests << " passed";

  if (d_config.verbose) {
    std::cout << simOutput << std::endl;
  }

  return result;
}

VerificationResult
TestbenchGenerator::compareSimulations(const std::string &i_workDir) {
  VerificationResult result;

  // Запускаем внутреннюю симуляцию
  auto internalResult = runInternalSimulation();

  // Запускаем Icarus верификацию
  auto icarusResult = runIcarusVerification(i_workDir);

  // Сравниваем результаты
  result.totalTests =
      d_hasSequential ? d_seqTestVectors.size() : d_testVectors.size();
  result.passedTests = 0;
  result.failedTests = 0;

  bool matchSuccess = (internalResult.success == icarusResult.success);
  bool matchPassedTests =
      (internalResult.passedTests == icarusResult.passedTests);
  bool matchFailedTests =
      (internalResult.failedTests == icarusResult.failedTests);
  bool matchTotalTests = (internalResult.totalTests == icarusResult.totalTests);

  // Поэлементное сравнение векторов только если Icarus-ветка их заполнила.
  // runIcarusVerification сейчас выставляет лишь счетчики и success по выводу
  // vvp, без копии d_testVectors в result.vectors — в этом случае
  // ограничиваемся согласованностью success и счетчиков.
  bool matchVectors = true;
  if (!icarusResult.vectors.empty()) {
    if (internalResult.vectors.size() == icarusResult.vectors.size()) {
      for (size_t i = 0; i < internalResult.vectors.size(); ++i) {
        const auto &internalVec = internalResult.vectors[i];
        const auto &icarusVec = icarusResult.vectors[i];
        if (internalVec.passed != icarusVec.passed ||
            internalVec.inputs != icarusVec.inputs ||
            internalVec.expected != icarusVec.expected ||
            internalVec.actual != icarusVec.actual) {
          matchVectors = false;
          break;
        }
      }
    } else {
      matchVectors = false;
    }
  }

  if (matchSuccess && matchPassedTests && matchFailedTests && matchTotalTests &&
      matchVectors) {
    result.success = true;
    result.passedTests = internalResult.passedTests;
    result.failedTests = internalResult.failedTests;
  } else {
    result.success = false;
    std::ostringstream errMsg;
    errMsg << "Internal and Icarus simulation results differ:";
    if (!matchSuccess)
      errMsg << " success(" << internalResult.success << " vs "
             << icarusResult.success << ")";
    if (!matchPassedTests)
      errMsg << " passedTests(" << internalResult.passedTests << " vs "
             << icarusResult.passedTests << ")";
    if (!matchFailedTests)
      errMsg << " failedTests(" << internalResult.failedTests << " vs "
             << icarusResult.failedTests << ")";
    if (!matchTotalTests)
      errMsg << " totalTests(" << internalResult.totalTests << " vs "
             << icarusResult.totalTests << ")";
    if (!matchVectors)
      errMsg << " vectors differ";
    result.errorMessage = errMsg.str();
  }

  result.simulatorOutput = icarusResult.simulatorOutput;
  result.simulatorExitCode = icarusResult.simulatorExitCode;

  return result;
}

// --- Утилиты ---

std::string
TestbenchGenerator::toVerilogLiteral(const std::vector<char> &i_values) {
  std::ostringstream ss;
  ss << i_values.size() << "'b";
  for (auto it = i_values.rbegin(); it != i_values.rend(); ++it) {
    ss << *it;
  }
  return ss.str();
}

std::vector<std::vector<char>>
TestbenchGenerator::parseIcarusOutput(const std::string &i_output) {
  std::vector<std::vector<char>> results;

  // Парсинг вывода для извлечения фактических значений
  // Формат: "Actual: out1=X, out2=Y, ..."
  std::regex actualRegex(R"(Actual:\s*(.+))");
  std::smatch match;

  std::string::const_iterator searchStart(i_output.cbegin());
  while (std::regex_search(searchStart, i_output.cend(), match, actualRegex)) {
    std::string actualStr = match[1].str();
    std::vector<char> values;

    std::regex valueRegex(R"(\w+\s*=\s*([01xzXZ]))");
    std::smatch valueMatch;
    std::string::const_iterator actualSearchStart(actualStr.cbegin());

    while (std::regex_search(actualSearchStart, actualStr.cend(), valueMatch,
                             valueRegex)) {
      char val = valueMatch[1].str()[0];
      values.push_back(val);
      actualSearchStart = valueMatch.suffix().first;
    }

    if (!values.empty()) {
      results.push_back(values);
    }

    searchStart = match.suffix().first;
  }

  return results;
}

std::vector<PortInfo>
TestbenchGenerator::parseGoldenModel(const std::string &filepath,
                                     std::string &moduleName) {
  std::vector<PortInfo> ports;
  std::ifstream file(filepath);

  if (!file.is_open()) {
    CG_LOG_ERROR << "Error: Cannot open golden model file: " << filepath;
    return ports;
  }

  std::string line;
  std::regex moduleRegex(R"(\bmodule\s+([a-zA-Z_][a-zA-Z0-9_]*))");
  std::regex portRegex(
      R"(\b(input|output)\s+(?:wire\s+|reg\s+)?(?:\[(\d+):(\d+)\]\s+)?([a-zA-Z0-9_,\s]+))");

  while (std::getline(file, line)) {
    std::smatch match;

    if (std::regex_search(line, match, moduleRegex)) {
      moduleName = match[1].str();
    }

    if (std::regex_search(line, match, portRegex)) {
      bool is_input = (match[1].str() == "input");

      int width = 1;
      if (match[2].matched && match[3].matched) {
        int msb = std::stoi(match[2].str());
        int lsb = std::stoi(match[3].str());
        width = std::abs(msb - lsb) + 1;
      }

      std::string port_name = match[4].str();
      port_name.erase(std::remove_if(port_name.begin(), port_name.end(),
                                     [](char c) {
                                       return c == ',' || c == ';' || c == ' ';
                                     }),
                      port_name.end());

      if (!port_name.empty()) {
        ports.push_back({port_name, width, is_input});
      }
    }
  }
  return ports;
}

bool TestbenchGenerator::generate(std::shared_ptr<OrientedGraph> graph,
                                  const std::string &goldenModelPath,
                                  const std::string &outputTbPath) {
  if (!graph)
    return false;

  std::string goldenModuleName;
  std::vector<PortInfo> goldenPorts =
      parseGoldenModel(goldenModelPath, goldenModuleName);

  if (goldenModuleName.empty() || goldenPorts.empty()) {
    CG_LOG_ERROR << "Error: Failed to parse golden model.";
    return false;
  }

  auto graphInputs = graph->getVerticesByType(VertexTypes::input);
  auto graphOutputs = graph->getVerticesByType(VertexTypes::output);

  int totalGoldenInputs = 0;
  int totalGoldenOutputs = 0;
  for (const auto &p: goldenPorts) {
    if (p.is_input)
      totalGoldenInputs += p.width;
    else
      totalGoldenOutputs += p.width;
  }

  std::ofstream tbFile(outputTbPath);
  if (!tbFile.is_open())
    return false;

  tbFile << "`timescale 1ns / 1ps\n\n";
  tbFile << "module tb_" << graph->getName() << "_vs_" << goldenModuleName
         << ";\n\n";

  tbFile << "    reg [" << (totalGoldenInputs - 1) << ":0] test_in;\n";
  tbFile << "    wire [" << (totalGoldenOutputs - 1) << ":0] golden_out;\n";
  tbFile << "    wire [" << (totalGoldenOutputs - 1) << ":0] graph_out;\n\n";

  tbFile << "    // --- Golden Model ---\n";
  tbFile << "    " << goldenModuleName << " golden_inst (\n";
  int in_offset = 0, out_offset = 0;
  for (size_t i = 0; i < goldenPorts.size(); ++i) {
    const auto &p = goldenPorts[i];
    tbFile << "        ." << p.name << "(";
    if (p.is_input) {
      if (p.width == 1)
        tbFile << "test_in[" << in_offset << "]";
      else
        tbFile << "test_in[" << (in_offset + p.width - 1) << ":" << in_offset
               << "]";
      in_offset += p.width;
    } else {
      if (p.width == 1)
        tbFile << "golden_out[" << out_offset << "]";
      else
        tbFile << "golden_out[" << (out_offset + p.width - 1) << ":"
               << out_offset << "]";
      out_offset += p.width;
    }
    tbFile << ")" << ((i == goldenPorts.size() - 1) ? "" : ",") << "\n";
  }
  tbFile << "    );\n\n";

  tbFile << "    // --- Graph Model ---\n";
  tbFile << "    " << graph->getName() << " graph_inst (\n";
  for (size_t i = 0; i < graphInputs.size(); ++i) {
    tbFile << "        ." << graphInputs[i]->getName() << "(test_in[" << i
           << "]),\n";
  }
  for (size_t i = 0; i < graphOutputs.size(); ++i) {
    tbFile << "        ." << graphOutputs[i]->getName() << "(graph_out[" << i
           << "])" << ((i == graphOutputs.size() - 1) ? "" : ",\n");
  }
  tbFile << "    );\n\n";

  tbFile << "    integer i;\n";
  tbFile << "    integer errors = 0;\n\n";
  tbFile << "    initial begin\n";
  tbFile << "        for (i = 0; i < (1 << " << totalGoldenInputs
         << "); i = i + 1) begin\n";
  tbFile << "            test_in = i;\n";
  tbFile << "            #10;\n";
  tbFile << "            if (golden_out !== graph_out) begin\n";
  tbFile << "                $display(\"ERROR! Input: %b | Golden: %b | Graph: "
            "%b\", test_in, golden_out, graph_out);\n";
  tbFile << "                errors = errors + 1;\n";
  tbFile << "            end\n";
  tbFile << "        end\n\n";
  tbFile << "        if (errors == 0) $display(\"SUCCESS! All combinations "
            "passed.\");\n";
  tbFile << "        else $display(\"FAILED with %0d errors.\", errors);\n";
  tbFile << "        $finish;\n";
  tbFile << "    end\n\n";
  tbFile << "endmodule\n";

  tbFile.close();
  return true;
}

// --- Последовательностная генерация ---

void TestbenchGenerator::detectClockSignals() {
  auto vertices = d_graph->getBaseVertexes();

  // Множества для уникальных имён
  std::set<std::string> clockSet;
  std::set<std::string> resetSet;
  std::set<std::string> enableSet;
  std::set<std::string> controlSet; // clk + rst + latch-en + set

  for (auto *seqVertex: vertices[VertexTypes::sequential]) {
    auto *seq = static_cast<GraphVertexSequential *>(seqVertex);

    if (auto *clk = seq->getClk()) {
      std::string name = std::string(clk->getRawName());
      clockSet.insert(name);
      controlSet.insert(name);
    }

    if (auto *en = seq->getEn()) {
      // Для защелок EN — управляющий сигнал: не data, но должен
      // подниматься при подаче стимула (иначе выход остаётся X).
      if (!seq->isFF()) {
        std::string name = std::string(en->getRawName());
        enableSet.insert(name);
        controlSet.insert(name);
      }
    }

    if (auto *rst = seq->getRst()) {
      std::string name = std::string(rst->getRawName());
      resetSet.insert(name);
      controlSet.insert(name);
    }

    if (auto *set = seq->getSet()) {
      std::string name = std::string(set->getRawName());
      controlSet.insert(name);
    }
  }

  d_clockNames.assign(clockSet.begin(), clockSet.end());
  d_resetNames.assign(resetSet.begin(), resetSet.end());
  d_enableNames.assign(enableSet.begin(), enableSet.end());

  // Входы данных — все входы минус управляющие сигналы
  d_dataInputNames.clear();
  for (const auto &inputName: d_inputNames) {
    if (controlSet.find(inputName) == controlSet.end()) {
      d_dataInputNames.push_back(inputName);
    }
  }

  CG_LOG_INFO << "TestbenchGenerator: detected " << d_clockNames.size()
              << " clock signals, " << d_resetNames.size() << " reset signals, "
              << d_enableNames.size() << " enable signals, "
              << d_dataInputNames.size() << " data inputs";
}

size_t TestbenchGenerator::generateSequentialTestVectors(size_t i_numCycles,
                                                         uint32_t i_seed) {
  size_t numDataInputs = d_dataInputNames.size();

  std::mt19937 gen;
  if (i_seed == 0) {
    std::random_device rd;
    gen.seed(rd());
  } else {
    gen.seed(i_seed);
  }
  std::uniform_int_distribution<> dist(0, 1);

  d_seqTestVectors.clear();

  for (size_t cycle = 0; cycle < i_numCycles; ++cycle) {
    SequentialTestVector stv;
    stv.dataInputs.resize(numDataInputs);
    for (size_t bit = 0; bit < numDataInputs; ++bit) {
      stv.dataInputs[bit] = dist(gen) ? '1' : '0';
    }
    stv.checkOutputs = false; // По умолчанию не проверяем
    d_seqTestVectors.push_back(std::move(stv));
  }

  CG_LOG_INFO << "TestbenchGenerator: generated " << i_numCycles
              << " sequential test vectors";

  return i_numCycles;
}

void TestbenchGenerator::addSequentialTestVector(
    const std::vector<char> &i_dataInputs,
    const std::vector<char> &i_expectedOutputs, bool i_checkOutputs) {
  if (i_dataInputs.size() != d_dataInputNames.size()) {
    throw std::invalid_argument(
        "TestbenchGenerator: data input vector size mismatch. Expected " +
        std::to_string(d_dataInputNames.size()) + ", got " +
        std::to_string(i_dataInputs.size()));
  }

  if (i_checkOutputs && !i_expectedOutputs.empty() &&
      i_expectedOutputs.size() != d_outputNames.size()) {
    throw std::invalid_argument(
        "TestbenchGenerator: expected output vector size mismatch");
  }

  d_seqTestVectors.push_back({i_dataInputs, i_expectedOutputs, i_checkOutputs});
}

void TestbenchGenerator::clearSequentialTestVectors() {
  d_seqTestVectors.clear();
}

std::string TestbenchGenerator::generateSequentialSignalDeclarations() const {
  std::ostringstream ss;

  // Тактовые сигналы
  if (!d_clockNames.empty()) {
    ss << "  // Clock signals\n";
    for (const auto &name: d_clockNames) {
      ss << "  reg " << name << ";\n";
    }
    ss << "\n";
  }

  // Сигналы сброса
  if (!d_resetNames.empty()) {
    ss << "  // Reset signals\n";
    for (const auto &name: d_resetNames) {
      ss << "  reg " << name << ";\n";
    }
    ss << "\n";
  }

  // Входные данные (без clk/rst)
  if (!d_dataInputNames.empty()) {
    ss << "  // Data input signals\n";
    for (const auto &name: d_dataInputNames) {
      ss << "  reg " << name << ";\n";
    }
    ss << "\n";
  }

  // Latch enable signals
  if (!d_enableNames.empty()) {
    ss << "  // Enable signals (latches)\n";
    for (const auto &name: d_enableNames) {
      ss << "  reg " << name << ";\n";
    }
    ss << "\n";
  }

  // Прочие управляющие входы (set и т.п.), не clk/rst/en/data
  std::set<std::string> declared;
  for (const auto &n: d_clockNames)
    declared.insert(n);
  for (const auto &n: d_resetNames)
    declared.insert(n);
  for (const auto &n: d_enableNames)
    declared.insert(n);
  for (const auto &n: d_dataInputNames)
    declared.insert(n);

  std::vector<std::string> otherInputs;
  for (const auto &name: d_inputNames) {
    if (declared.find(name) == declared.end()) {
      otherInputs.push_back(name);
    }
  }

  if (!otherInputs.empty()) {
    ss << "  // Other control signals\n";
    for (const auto &name: otherInputs) {
      ss << "  reg " << name << ";\n";
    }
    ss << "\n";
  }

  // Выходные провода
  ss << "  // Output signals\n";
  for (const auto &name: d_outputNames) {
    ss << "  wire " << name << "_dut;\n";
  }
  ss << "\n";

  // Переменные для тестирования
  ss << "  // Test control variables\n";
  ss << "  integer test_num;\n";
  ss << "  integer errors;\n";
  ss << "  integer passed;\n";
  ss << "\n";

  return ss.str();
}

std::string TestbenchGenerator::generateClockBlock() const {
  std::ostringstream ss;

  for (const auto &clkName: d_clockNames) {
    ss << "  // Clock generation for " << clkName << "\n";
    ss << "  always #" << (d_config.clockPeriod / 2) << " " << clkName << " = ~"
       << clkName << ";\n\n";
  }

  return ss.str();
}

std::string TestbenchGenerator::generateSequentialDUTInstantiation() const {
  std::ostringstream ss;

  ss << "  // Device Under Test instantiation\n";
  ss << "  " << d_graph->getName() << " dut (\n";

  // Все входы (включая clk/rst)
  for (size_t i = 0; i < d_inputNames.size(); ++i) {
    ss << "    ." << d_inputNames[i] << "(" << d_inputNames[i] << ")";
    if (i < d_inputNames.size() - 1 || !d_outputNames.empty()) {
      ss << ",";
    }
    ss << "\n";
  }

  // Выходы
  for (size_t i = 0; i < d_outputNames.size(); ++i) {
    ss << "    ." << d_outputNames[i] << "(" << d_outputNames[i] << "_dut)";
    if (i < d_outputNames.size() - 1) {
      ss << ",";
    }
    ss << "\n";
  }

  ss << "  );\n\n";

  return ss.str();
}

std::string TestbenchGenerator::generateSequentialStimulusBlock() const {
  std::ostringstream ss;

  // Определяем тип фронта для тактового сигнала
  // По умолчанию posedge, но проверяем через GraphVertexSequential
  bool useNegedge = false;
  auto vertices = d_graph->getBaseVertexes();
  for (auto *seqVertex: vertices[VertexTypes::sequential]) {
    auto *seq = static_cast<GraphVertexSequential *>(seqVertex);
    if (seq->isFF() && seq->isNegedge()) {
      useNegedge = true;
      break;
    }
  }
  std::string edgeType = useNegedge ? "negedge" : "posedge";

  ss << "  // Main test block\n";
  ss << "  initial begin\n";
  ss << "    // Initialize\n";
  ss << "    errors = 0;\n";
  ss << "    passed = 0;\n";
  ss << "    test_num = 0;\n";
  ss << "\n";

  // Инициализация clk
  for (const auto &clkName: d_clockNames) {
    ss << "    " << clkName << " = 1'b0;\n";
  }

  // Инициализация сигналов сброса — начинаем с активного состояния
  for (const auto &rstName: d_resetNames) {
    if (d_config.resetActiveValue == 0) {
      // Active-low reset: начинаем со сброса (= 0)
      ss << "    " << rstName << " = 1'b0;\n";
    } else {
      // Active-high reset: начинаем со сброса (= 1)
      ss << "    " << rstName << " = 1'b1;\n";
    }
  }

  // Инициализация data-входов
  for (const auto &name: d_dataInputNames) {
    ss << "    " << name << " = 1'b0;\n";
  }

  // Latch enable — начинаем закрытыми
  for (const auto &enName: d_enableNames) {
    ss << "    " << enName << " = 1'b0;\n";
  }

  // Инициализация прочих управляющих входов
  std::set<std::string> declaredSet;
  for (const auto &n: d_clockNames)
    declaredSet.insert(n);
  for (const auto &n: d_resetNames)
    declaredSet.insert(n);
  for (const auto &n: d_enableNames)
    declaredSet.insert(n);
  for (const auto &n: d_dataInputNames)
    declaredSet.insert(n);
  for (const auto &name: d_inputNames) {
    if (declaredSet.find(name) == declaredSet.end()) {
      ss << "    " << name << " = 1'b0;\n";
    }
  }

  ss << "\n";
  ss << "    $display(\"========================================\");\n";
  ss << "    $display(\"Starting sequential testbench for "
     << d_graph->getName() << "\");\n";
  ss << "    $display(\"Total test cycles: " << d_seqTestVectors.size()
     << "\");\n";
  ss << "    $display(\"========================================\");\n";
  ss << "\n";

  // Фаза сброса
  ss << "    // Reset phase\n";
  ss << "    #" << d_config.resetDuration << ";\n";

  // Снимаем сброс
  for (const auto &rstName: d_resetNames) {
    if (d_config.resetActiveValue == 0) {
      // Active-low: снимаем сброс, устанавливаем 1
      ss << "    " << rstName << " = 1'b1;\n";
    } else {
      // Active-high: снимаем сброс, устанавливаем 0
      ss << "    " << rstName << " = 1'b0;\n";
    }
  }

  if (!d_clockNames.empty()) {
    ss << "    @(" << edgeType << " " << d_clockNames[0] << ");\n";
  }
  ss << "\n";

  // Генерируем тестовые векторы по тактам
  for (size_t i = 0; i < d_seqTestVectors.size(); ++i) {
    const auto &stv = d_seqTestVectors[i];

    ss << "    // Test cycle " << i << "\n";
    ss << "    test_num = " << i << ";\n";

    // Устанавливаем data-входы
    for (size_t j = 0; j < d_dataInputNames.size() && j < stv.dataInputs.size();
         ++j) {
      ss << "    " << d_dataInputNames[j] << " = 1'b" << stv.dataInputs[j]
         << ";\n";
    }

    // Для защелок поднимаем EN, иначе данные не защёлкиваются
    for (const auto &enName: d_enableNames) {
      ss << "    " << enName << " = 1'b1;\n";
    }

    // Ждём фронта clk или задержку для latch
    if (!d_clockNames.empty()) {
      ss << "    @(" << edgeType << " " << d_clockNames[0] << ");\n";
      ss << "    #1;\n"; // Небольшая задержка для установки выходов
    } else {
      ss << "    #" << d_config.stimulusDelay << ";\n";
    }

    // Вывод текущего состояния
    ss << "    $display(\"Cycle %0d: \", test_num";
    for (const auto &outName: d_outputNames) {
      ss << ", \" " << outName << "=%b\", " << outName << "_dut";
    }
    ss << ");\n";

    // Проверка ожидаемых значений (если задано)
    if (stv.checkOutputs && !stv.expectedOutputs.empty()) {
      ss << "    if (";
      for (size_t j = 0; j < d_outputNames.size(); ++j) {
        ss << d_outputNames[j] << "_dut === 1'b" << stv.expectedOutputs[j];
        if (j < d_outputNames.size() - 1) {
          ss << " && ";
        }
      }
      ss << ") begin\n";
      ss << "      passed = passed + 1;\n";
      ss << "      $display(\"PASS: Test %0d\", test_num);\n";
      ss << "    end else begin\n";
      ss << "      errors = errors + 1;\n";
      ss << "      $display(\"FAIL: Test %0d\", test_num);\n";
      ss << "    end\n";
    } else {
      ss << "    passed = passed + 1;\n";
    }

    // Закрываем защелку до следующего цикла
    for (const auto &enName: d_enableNames) {
      ss << "    " << enName << " = 1'b0;\n";
    }

    ss << "\n";
  }

  // Итоговый отчет
  ss << "    // Final report\n";
  ss << "    $display(\"========================================\");\n";
  ss << "    $display(\"Test Summary:\");\n";
  ss << "    $display(\"  Total:  %0d\", " << d_seqTestVectors.size() << ");\n";
  ss << "    $display(\"  Passed: %0d\", passed);\n";
  ss << "    $display(\"  Failed: %0d\", errors);\n";
  ss << "    if (errors == 0) begin\n";
  ss << "      $display(\"STATUS: ALL TESTS PASSED\");\n";
  ss << "    end else begin\n";
  ss << "      $display(\"STATUS: SOME TESTS FAILED\");\n";
  ss << "    end\n";
  ss << "    $display(\"========================================\");\n";
  ss << "\n";
  ss << "    $finish;\n";
  ss << "  end\n";

  return ss.str();
}

} // namespace CG_Graph
